import { useEffect, useState } from 'react'
import { api } from '../api'
import { MultiSelect } from './MultiSelect'
import { PlanActualChart } from './Charts'
import { num } from './UI'
export default function ProcessFlowMonitor({data,date,productId,onChange}:{data:any,date:string,productId:number,onChange:()=>void}){
 const [branches,setBranches]=useState<string[]>([]),[variants,setVariants]=useState<string[]>([]),[selected,setSelected]=useState<any>(null),[actual,setActual]=useState(''),[reject,setReject]=useState('0'),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{setSelected(null);setBranches([]);setVariants([])},[data.flow.id,date,data.period?.start])
 const isRange=Boolean(data.period?.is_range)
 const active=data.stages.filter((s:any)=>s.active)
 const options=(field:string)=>[...new Set<string>(active.map((s:any)=>String(s[field]||'')))].filter(Boolean).map(value=>({value,label:value}))
 const stages=active.filter((s:any)=>(!branches.length||branches.includes(s.branch))&&(!variants.length||variants.includes(s.variant)))
 const points=stages.filter((s:any)=>s.plan!=null&&s.actual!=null).map((s:any)=>({id:s.id,label:s.name,plan:s.plan,actual:s.actual,compliance:s.plan>0?s.actual/s.plan:null,gap:s.actual-s.plan}))
 function choose(s:any){setSelected(s);setActual(s.actual==null?'':String(s.actual));setReject(String(s.reject||0));setReason('');setError('')}
 async function save(){setBusy(true);setError('');try{await api('/process/entry',{method:'POST',body:JSON.stringify({summary_date:date,product_id:productId,route_operation_id:selected.route_operation_id,plan_qty:selected.plan||0,actual_qty:Number(actual),good_qty:Number(actual)-Number(reject),reject_qty:Number(reject),opening_wip:0,closing_wip:0,remarks:reason,source:'MANUAL'})});setSelected(null);onChange()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel"><h2>Approved process flow R{data.flow.revision}</h2><p>Effective {data.flow.effective_from}. {isRange?'Plan, actual and rejection are working-day averages for the selected period. OFF days and missing actual days are not treated as zero.':'Each stage has its own allocation. Parent dispatch alone feeds MIS. Blank plan or actual means missing data.'}</p>{data.period&&<div className="notice">{data.period.working_days} working day(s) included • {data.period.off_days} OFF day(s) excluded{data.period.truncated_to_flow?' • Period starts at this flow revision effective date':''}</div>}<div className="form-row"><MultiSelect value={branches} onChange={setBranches} options={options('branch')} placeholder="All branches"/><MultiSelect value={variants} onChange={setVariants} options={options('variant')} placeholder="All variants"/></div>
 <PlanActualChart rows={points} metric="qty" verticalLabels onSelect={isRange?undefined:r=>choose(stages.find((s:any)=>s.id===r.id))}/>
 <div className="table-wrap"><table><thead><tr><th>Stage / Source</th><th>Branch / Variant</th><th>Role / Vendor</th><th>Predecessors</th><th>Allocated</th><th>{isRange?'Avg plan':'Daily plan'}</th><th>{isRange?'Avg actual':'Actual'}</th><th>{isRange?'Avg reject':'Reject'}</th><th>Data days</th><th></th></tr></thead><tbody>{stages.map((s:any)=><tr key={s.id}><td><b>{s.name}</b><br/>{s.code} ({s.source_column}){s.parent_dispatch&&<small>Parent MIS dispatch</small>}</td><td>{s.branch}<br/>{s.variant}</td><td>{s.role}<br/>{s.vendor|| (s.role.startsWith('VENDOR')?'Vendor pending':'')}</td><td>{s.predecessors.join(', ')||'Start'}</td><td>{s.allocated_qty==null?'Pending':num(s.allocated_qty)}<br/>{s.allocation_reference}</td><td>{s.plan==null?'Pending':num(s.plan)}</td><td>{s.actual==null?'Missing':num(s.actual)}</td><td>{s.reject==null?'—':num(s.reject)}</td><td>{s.days_with_data??(s.actual==null?0:1)}{data.period?' / '+data.period.working_days:''}</td><td>{!isRange&&<button className="small secondary" onClick={()=>choose(s)}>Enter actual</button>}</td></tr>)}</tbody></table></div>
 {selected&&!isRange&&<div className="panel"><h3>{selected.name}: {date}</h3><div className="form-row"><label>Actual pieces<input type="number" min="0" step="1" value={actual} onChange={e=>setActual(e.target.value)}/></label><label>Rejected pieces<input type="number" min="0" step="1" value={reject} onChange={e=>setReject(e.target.value)}/></label><label>Correction reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||actual===''} onClick={save}>Save actual</button><button className="secondary" onClick={()=>setSelected(null)}>Cancel</button></div>{error&&<p className="error">{error}</p>}</div>}
 <details><summary>Deferred and reference columns</summary><ul>{data.stages.filter((s:any)=>!s.active).map((s:any)=><li key={s.id}>{s.source_column}: {s.name}{s.alias_of?` (alias of ${s.alias_of})`:''}</li>)}</ul></details></section>
}
