import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { api, downloadApi } from '../api'
import { ScopeFilters, ScopeValues, appendScope } from '../components/ScopeFilters'
import { MultiSelect } from '../components/MultiSelect'
import { PageHeader, Status } from '../components/UI'

const emptyScope:ScopeValues={plant:[],productGroup:[],customerId:[],productId:[]}
const emptyPlan:any={containment_action:'',why1:'',why2:'',why3:'',why4:'',why5:'',root_cause:'',corrective_action:'',preventive_action:'',verification_method:'',verification_result:'',effectiveness_check_date:'',effectiveness_result:'',lessons_learned:''}

export default function Actions(){
 const [params]=useSearchParams()
 const queryDate=params.get('date')||new Date().toISOString().slice(0,10)
 const queryProduct=params.get('product_id')||''
 const queryProblem=params.get('problem')||''
 const [rows,setRows]=useState<any[]>([]); const [products,setProducts]=useState<any[]>([]); const [options,setOptions]=useState<any>({}); const [users,setUsers]=useState<any[]>([]); const [routes,setRoutes]=useState<any[]>([]); const [machines,setMachines]=useState<any[]>([]); const [filter,setFilter]=useState<string[]>([]); const [scope,setScope]=useState<ScopeValues>(queryProduct?{...emptyScope,productId:[queryProduct]}:emptyScope)
 const [err,setErr]=useState(''); const [message,setMessage]=useState(''); const [linkedReview,setLinkedReview]=useState<any>(null)
 const [form,setForm]=useState<any>({reference_date:queryDate,product_id:queryProduct,route_operation_id:'',machine_id:'',problem_category:'Production',problem_description:queryProblem,action_description:'',owner_id:'',due_at:'',priority:'HIGH'})
 const [selected,setSelected]=useState<any>(null); const [plan,setPlan]=useState<any>(emptyPlan); const [attachments,setAttachments]=useState<any[]>([]); const [planBusy,setPlanBusy]=useState(false); const [attachFile,setAttachFile]=useState<File|null>(null); const [caption,setCaption]=useState('')
 const eligible=useMemo(()=>products.filter(p=>(!scope.plant.length||scope.plant.includes(String(p.plant||'')))&&(!scope.productGroup.length||scope.productGroup.includes(String(p.product_group||'')))&&(!scope.customerId.length||scope.customerId.includes(String(p.customer_id)))),[products,scope])
 async function load(){try{const q=appendScope(new URLSearchParams(),scope);if(filter.length)q.set('status',filter.join(','));setRows(await api(`/actions${q.toString()?`?${q}`:''}`));setErr('')}catch(e:any){setErr(e.message)}}
 useEffect(()=>{load(); Promise.all([api('/masters/products'),api('/masters/filter-options'),api('/masters/users'),api('/masters/machines')]).then(([p,o,u,m]:any)=>{setProducts(p);setOptions(o);setUsers(u);setMachines(m);const preferred=queryProduct&&p.some((x:any)=>String(x.id)===queryProduct)?queryProduct:(p[0]?String(p[0].id):'');setForm((f:any)=>({...f,product_id:preferred}))}).catch((e:any)=>setErr(e.message))},[])
 useEffect(()=>{load()},[filter,scope.plant,scope.productGroup,scope.customerId,scope.productId])
 useEffect(()=>{if(scope.productId.length===1)setForm((f:any)=>({...f,product_id:scope.productId[0]}));else if(!eligible.some(p=>String(p.id)===String(form.product_id))&&eligible[0])setForm((f:any)=>({...f,product_id:String(eligible[0].id)}))},[scope.productId,eligible])
 useEffect(()=>{if(form.product_id)api(`/masters/routes/${form.product_id}`).then((x:any)=>{const ops=x[0]?.operations||[]; setRoutes(ops); setForm((f:any)=>({...f,route_operation_id:ops[0]?String(ops[0].route_operation_id):''}))}).catch((e:any)=>setErr(e.message))},[form.product_id])
 useEffect(()=>{api(`/reviews/active?review_date=${form.reference_date}`).then((r:any)=>setLinkedReview(r||null)).catch(()=>setLinkedReview(null))},[form.reference_date])
 async function create(e:React.FormEvent){
   e.preventDefault(); setErr(''); setMessage('')
   if(!form.product_id){setErr('Select a product before creating the action.');return}
   try{
     const created:any=await api('/actions',{method:'POST',body:JSON.stringify({reference_date:form.reference_date,problem_category:form.problem_category,problem_description:form.problem_description,action_description:form.action_description,owner_id:form.owner_id?Number(form.owner_id):null,due_at:form.due_at?new Date(form.due_at).toISOString():null,priority:form.priority,contexts:[{context_date:form.reference_date,product_id:Number(form.product_id),route_operation_id:form.route_operation_id?Number(form.route_operation_id):null,machine_id:form.machine_id?Number(form.machine_id):null}]})})
     const reviewIds=created.review_session_ids||[]
     setMessage(`${created.action_no} created. Standard Why-Why plan opened${reviewIds.length?` and linked to review #${reviewIds[0]}`:''}.`)
     setForm((f:any)=>({...f,problem_description:'',action_description:''})); await load(); await openPlan(created)
   }catch(e:any){setErr(`Unable to create action: ${e.message}`)}
 }
 async function setStatus(id:number,status:string){const comment=prompt('Follow-up / closure comment');if(comment===null)return;try{await api(`/actions/${id}`,{method:'PATCH',body:JSON.stringify({status,comment:comment||`Status changed to ${status}`,closure_remark:status==='CLOSED'?(comment||`Closed`):null})});setMessage(`Action updated to ${status}.`);load();if(selected?.id===id)openPlan({...selected,id})}catch(e:any){setErr(e.message)}}
 async function openPlan(a:any){try{setPlanBusy(true);setErr('');const r:any=await api(`/actions/${a.id}/plan`);setSelected(r.action);setPlan({...emptyPlan,...r.plan,effectiveness_check_date:r.plan?.effectiveness_check_date||''});setAttachments(r.attachments||[])}catch(e:any){setErr(e.message)}finally{setPlanBusy(false)}}
 async function savePlan(){if(!selected)return;try{setPlanBusy(true);const payload={...plan,effectiveness_check_date:plan.effectiveness_check_date||null};const r:any=await api(`/actions/${selected.id}/plan`,{method:'PUT',body:JSON.stringify(payload)});setPlan({...emptyPlan,...r.plan,effectiveness_check_date:r.plan?.effectiveness_check_date||''});setSelected(r.action);setAttachments(r.attachments||[]);setMessage(`${selected.action_no} Why-Why plan saved.`);await load()}catch(e:any){setErr(e.message)}finally{setPlanBusy(false)}}
 async function uploadAttachment(){if(!selected||!attachFile)return;try{setPlanBusy(true);const fd=new FormData();fd.append('file',attachFile);if(caption)fd.append('caption',caption);await api(`/actions/${selected.id}/attachments`,{method:'POST',body:fd});setAttachFile(null);setCaption('');await openPlan(selected);setMessage(`Attachment added to ${selected.action_no}.`)}catch(e:any){setErr(e.message)}finally{setPlanBusy(false)}}
 async function downloadPlanPdf(){if(!selected)return;try{setErr('');await downloadApi(`/actions/${selected.id}/pdf`,`${selected.action_no}_WhyWhy_ActionPlan.pdf`)}catch(e:any){setErr(e.message)}}
 return <><PageHeader title="Action Management" subtitle="One standard Why-Why action plan for Production, Quality, OEE/Loss, Vendor, Schedule and all other reviews." actions={<MultiSelect value={filter} onChange={setFilter} placeholder="All Status" searchable={false} options={["OPEN","IN_PROGRESS","BLOCKED","CLOSED"].map(x=>({value:x,label:x.replaceAll('_',' ')}))}/>}/>
 <ScopeFilters value={scope} onChange={setScope} options={options} products={products}/>
 {err&&<div className="error">{err}</div>}{message&&<div className="notice">{message}</div>}
 <div className="two-col wide-left"><section className="panel"><div className="table-wrap"><table><thead><tr><th>No.</th><th>Plant / Group</th><th>Context</th><th>Problem / Initial action</th><th>Why-Why</th><th>Review</th><th>Due</th><th>Age</th><th>Priority</th><th>Status</th><th>Update</th></tr></thead><tbody>{rows.map(a=><tr key={a.id} className={a.overdue?'row-overdue':''}><td><b>{a.action_no}</b><br/><small>{a.reference_date}</small></td><td>{a.contexts?.map((c:any,i:number)=><div key={i}>{c.plant||'—'}<br/><small>{c.product_group||'—'}</small></div>)}</td><td>{a.contexts?.map((c:any)=><div key={`${c.date}-${c.product_id}-${c.route_operation_id}`}>{c.product}<br/><small>{c.operation||'Product level'}{c.machine_id?` • Machine #${c.machine_id}`:''}</small></div>)}</td><td><b>{a.problem_description}</b><br/><small>{a.action_description}</small></td><td><button className="secondary small" onClick={()=>openPlan(a)}>Why-Why {a.whywhy_completion_percent||0}%</button><br/><small>{a.whywhy_can_close?'Closure ready':'Analysis pending'}</small></td><td>{a.review_session_ids?.length?a.review_session_ids.map((x:number)=>`#${x}`).join(', '):'—'}</td><td>{a.due_at?.replace('T',' ').slice(0,16)||'—'}</td><td>{a.age_days}d</td><td><Status value={a.priority}/></td><td><Status value={a.status}/></td><td><select value={a.status} onChange={e=>setStatus(a.id,e.target.value)}><option>OPEN</option><option>IN_PROGRESS</option><option>BLOCKED</option><option>CLOSED</option></select></td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2>Raise action</h2>{linkedReview&&<div className="notice">Review #{linkedReview.id} is active for {form.reference_date}. This action will be linked automatically.</div>}<div className="data-note">Raise the issue quickly here. The same standard Why-Why plan is then used for every action across the web app.</div><form onSubmit={create}><label>Date<input type="date" value={form.reference_date} onChange={e=>setForm({...form,reference_date:e.target.value})}/></label><label>Product<MultiSelect className="manual-search-select" value={form.product_id?[String(form.product_id)]:[]} onChange={v=>setForm({...form,product_id:v.at(-1)||''})} placeholder="Select Product" options={eligible.map(p=>({value:String(p.id),label:p.name}))}/></label><label>Operation<MultiSelect className="manual-search-select" value={form.route_operation_id?[String(form.route_operation_id)]:[]} onChange={v=>setForm({...form,route_operation_id:v.at(-1)||''})} placeholder="Product-level action" options={routes.map(o=>({value:String(o.route_operation_id),label:o.operation}))}/></label><label>Machine (optional)<MultiSelect className="manual-search-select" value={form.machine_id?[String(form.machine_id)]:[]} onChange={v=>setForm({...form,machine_id:v.at(-1)||''})} placeholder="No machine" options={machines.map(m=>({value:String(m.id),label:`${m.code} — ${m.name}`}))}/></label><label>Problem category<input value={form.problem_category} onChange={e=>setForm({...form,problem_category:e.target.value})}/></label><label>Problem<textarea required value={form.problem_description} onChange={e=>setForm({...form,problem_description:e.target.value})}/></label><label>Immediate / proposed action<textarea required value={form.action_description} onChange={e=>setForm({...form,action_description:e.target.value})}/></label><label>Owner<MultiSelect className="manual-search-select" value={form.owner_id?[String(form.owner_id)]:[]} onChange={v=>setForm({...form,owner_id:v.at(-1)||''})} placeholder="Unassigned" options={users.map(u=>({value:String(u.id),label:u.full_name}))}/></label><label>Due<input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><button>Create action & open Why-Why</button></form></section></div>
 {selected&&<section className="panel whywhy-panel"><div className="panel-title"><div><h2>Standard Why-Why Action Plan — {selected.action_no}</h2><p>{selected.problem_description}</p></div><div className="form-row compact"><button type="button" className="secondary small" onClick={downloadPlanPdf}>Download PDF</button><Status value={selected.status}/></div></div>{planBusy&&<div className="notice">Saving / loading…</div>}
 <div className="whywhy-grid"><div><h3>1. Immediate containment</h3><label>Containment / immediate action<textarea value={plan.containment_action||''} onChange={e=>setPlan({...plan,containment_action:e.target.value})}/></label></div><div><h3>2. Why-Why analysis</h3>{[1,2,3,4,5].map(n=><label key={n}>Why {n}<textarea value={plan[`why${n}`]||''} onChange={e=>setPlan({...plan,[`why${n}`]:e.target.value})} placeholder={n===1?'Why did the problem occur?':'Why did the previous cause occur?'}/></label>)}<div className="data-note">Continue only as far as needed to reach the true root cause; Why 3–5 are not forced if the root cause is already demonstrated.</div></div><div><h3>3. Root cause & actions</h3><label>Root cause<textarea value={plan.root_cause||''} onChange={e=>setPlan({...plan,root_cause:e.target.value})}/></label><label>Corrective action<textarea value={plan.corrective_action||''} onChange={e=>setPlan({...plan,corrective_action:e.target.value})}/></label><label>Preventive / systemic action<textarea value={plan.preventive_action||''} onChange={e=>setPlan({...plan,preventive_action:e.target.value})}/></label></div><div><h3>4. Verification & effectiveness</h3><label>Verification method<textarea value={plan.verification_method||''} onChange={e=>setPlan({...plan,verification_method:e.target.value})}/></label><label>Verification result<textarea value={plan.verification_result||''} onChange={e=>setPlan({...plan,verification_result:e.target.value})}/></label><label>Effectiveness check date<input type="date" value={plan.effectiveness_check_date||''} onChange={e=>setPlan({...plan,effectiveness_check_date:e.target.value})}/></label><label>Effectiveness result<textarea value={plan.effectiveness_result||''} onChange={e=>setPlan({...plan,effectiveness_result:e.target.value})}/></label><label>Lessons learned / horizontal deployment<textarea value={plan.lessons_learned||''} onChange={e=>setPlan({...plan,lessons_learned:e.target.value})}/></label></div></div>
 <div className="whywhy-footer"><div><b>Closure readiness: {plan.completion_percent||0}%</b><br/><small>{plan.can_close?'Required Why-Why fields complete. Action may be closed after review.':`Missing: ${(plan.missing_for_close||[]).join(', ')}`}</small></div><button onClick={savePlan} disabled={planBusy}>Save Why-Why plan</button></div>
 <div className="attachment-box"><h3>Attachments / Evidence</h3><p>Allowed: PDF, PNG, JPG, WebP, XLSX/XLSM, DOCX, PPTX, TXT and CSV. Default maximum size: 25 MB.</p><div className="form-row"><label>File<input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.xlsx,.xlsm,.docx,.pptx,.txt,.csv" onChange={e=>setAttachFile(e.target.files?.[0]||null)}/></label><label>Caption<input value={caption} maxLength={500} onChange={e=>setCaption(e.target.value)} placeholder="Defect photo, 5-Why, trial report, SOP…"/></label><button type="button" onClick={uploadAttachment} disabled={!attachFile||planBusy}>Upload</button></div>{attachments.length?<div className="table-wrap"><table><thead><tr><th>File</th><th>Caption</th><th>Size</th><th>Uploaded</th><th></th></tr></thead><tbody>{attachments.map((x:any)=><tr key={x.id}><td>{x.file_name}</td><td>{x.caption||'—'}</td><td>{Math.max(1,Math.round((x.size_bytes||0)/1024))} KB</td><td>{String(x.created_at||'').replace('T',' ').slice(0,16)}</td><td><button className="secondary small" onClick={()=>downloadApi(`/actions/${selected.id}/attachments/${x.id}`,x.file_name)}>Download</button></td></tr>)}</tbody></table></div>:<div className="empty">No attachments yet.</div>}</div>
 </section>}
 </>
}
