import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../api'
import { Kpi, PageHeader, Status, money, num } from '../components/UI'
import { MultiSelect } from '../components/MultiSelect'

const monthNow=()=>new Date().toISOString().slice(0,7)+'-01'
const today=()=>new Date().toISOString().slice(0,10)

export default function CapacityPlanning(){
 const [params]=useSearchParams()
 const [products,setProducts]=useState<any[]>([]);const [machines,setMachines]=useState<any[]>([])
 const [pid,setPid]=useState('');const [month,setMonth]=useState(monthNow());const [plan,setPlan]=useState<any>(null);const [opId,setOpId]=useState('')
 const [alloc,setAlloc]=useState<Record<string,string>>({});const [history,setHistory]=useState<any>({});const [allocationHistory,setAllocationHistory]=useState<any[]>([]);const [machineLoading,setMachineLoading]=useState<any>(null)
 const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');const [reason,setReason]=useState('Monthly machine allocation approved')
 const [setup,setSetup]=useState<any>({machine_id:'',effective_from:today(),priority:1,ideal_cycle_time_sec:'',standard_cycle_time_sec:'',pieces_per_cycle:1,operators_per_machine:'',shifts_per_day:3,shift_minutes:480,planned_break_minutes:30,planning_efficiency_percent:85,reason:'Approved capacity master revision'})
 useEffect(()=>{Promise.all([api('/masters/products'),api('/masters/machines')]).then(([p,m]:any)=>{setProducts(p);setMachines(m);const requested=params.get('product_id');if(requested&&p.some((x:any)=>String(x.id)===requested))setPid(requested);else if(p[0])setPid(String(p[0].id));if(m[0])setSetup((x:any)=>({...x,machine_id:String(m[0].id)}))})},[])
 async function load(){if(!pid)return;setBusy(true);setMsg('');try{const p:any=await api(`/capacity/plan?product_id=${pid}&month=${month}`);setPlan(p);const next=p.operations.some((x:any)=>String(x.route_operation_id)===opId)?opId:String(p.operations[0]?.route_operation_id||'');setOpId(next)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[pid,month])
 async function loadMachineLoading(){try{setMachineLoading(await api(`/capacity/machine-loading?month=${month}`))}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{loadMachineLoading()},[month])
 const operation=useMemo(()=>plan?.operations?.find((x:any)=>String(x.route_operation_id)===opId),[plan,opId])
 useEffect(()=>{if(!operation)return;const x:Record<string,string>={};operation.machines.forEach((m:any)=>x[String(m.machine_id)]=String(m.allocation_qty));setAlloc(x);loadHistory()},[operation?.route_operation_id,operation?.allocation_revision,setup.machine_id])
 async function loadHistory(){if(!opId)return;const q=`route_operation_id=${opId}${setup.machine_id?`&machine_id=${setup.machine_id}`:''}`;const [h,a]:any=await Promise.all([api(`/capacity/master-history?${q}`),api(`/capacity/allocations/history?product_id=${pid}&route_operation_id=${opId}&month=${month}`)]);setHistory(h);setAllocationHistory(a)}
 function autoAllocate(){if(!operation)return;let remaining=Math.round(Number(operation.schedule_qty));const x:Record<string,string>={};const usable=[...operation.machines].filter((m:any)=>m.complete&&Number(m.available_capacity_qty||0)>0).sort((a:any,b:any)=>a.priority-b.priority||a.machine_code.localeCompare(b.machine_code));operation.machines.forEach((m:any)=>x[String(m.machine_id)]='0');usable.forEach((m:any)=>{if(remaining<=0)return;const q=Math.min(remaining,Math.floor(Number(m.available_capacity_qty||0)));x[String(m.machine_id)]=String(q);remaining-=q});setAlloc(x)}
 const allocated=operation?.machines?.reduce((s:number,m:any)=>s+Number(alloc[String(m.machine_id)]||0),0)||0
 const allocationOverCapacity=operation?.machines?.some((m:any)=>Number(alloc[String(m.machine_id)]||0)>Number(m.available_capacity_qty??m.capacity_qty)+0.001)||false
 const allocationOverSchedule=operation?allocated>Number(operation.schedule_qty)+0.001:false
 const liveOperators=operation?Math.ceil(operation.machines.reduce((s:number,m:any)=>s+(m.capacity_qty?Number(alloc[String(m.machine_id)]||0)/m.capacity_qty*m.operators_per_machine:0),0)):0
 const liveRunCost=operation?operation.machines.reduce((s:number,m:any)=>s+Number(alloc[String(m.machine_id)]||0)*Number(m.estimated_cost_per_piece||0),0):0
 async function saveAllocation(){if(!operation)return;setBusy(true);try{const r:any=await api('/capacity/allocations',{method:'POST',body:JSON.stringify({product_id:Number(pid),route_operation_id:Number(opId),month,effective_from:month,reason,allocations:operation.machines.map((m:any)=>({machine_id:m.machine_id,allocated_qty:Number(alloc[String(m.machine_id)]||0)}))})});setMsg(`Machine allocation revision R${r.revision_no} saved: ${num(r.allocated_qty)} allocated / ${num(r.schedule_qty)} schedule${Number(r.allocation_gap||0)>0?` • shortage ${num(r.allocation_gap)}`:''}.`);await load();await loadMachineLoading()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function saveMaster(kind:'map'|'cycle'|'operator'|'capacity'){
  if(!opId||!setup.machine_id)return;setBusy(true);setMsg('')
  try{
   if(kind==='map')await api('/masters/machine-maps',{method:'POST',body:JSON.stringify({route_operation_id:Number(opId),machine_id:Number(setup.machine_id),effective_from:setup.effective_from,priority:Number(setup.priority),reason:setup.reason})})
   if(kind==='cycle')await api('/masters/cycle-times',{method:'POST',body:JSON.stringify({route_operation_id:Number(opId),machine_id:Number(setup.machine_id),effective_from:setup.effective_from,ideal_cycle_time_sec:Number(setup.ideal_cycle_time_sec),standard_cycle_time_sec:setup.standard_cycle_time_sec===''?null:Number(setup.standard_cycle_time_sec),pieces_per_cycle:Number(setup.pieces_per_cycle),reason:setup.reason})})
   if(kind==='operator')await api('/capacity/operator-requirements',{method:'POST',body:JSON.stringify({route_operation_id:Number(opId),machine_id:Number(setup.machine_id),effective_from:setup.effective_from,operators_per_machine:Number(setup.operators_per_machine),reason:setup.reason})})
   if(kind==='capacity')await api('/capacity/machine-settings',{method:'POST',body:JSON.stringify({machine_id:Number(setup.machine_id),effective_from:setup.effective_from,shifts_per_day:Number(setup.shifts_per_day),shift_minutes:Number(setup.shift_minutes),planned_break_minutes:Number(setup.planned_break_minutes),planning_efficiency:Number(setup.planning_efficiency_percent)/100,reason:setup.reason})})
   setMsg(`${kind} revision saved from ${setup.effective_from}. Earlier effective history is retained.`);await load();await loadHistory()
  }catch(e:any){setMsg(e.message)}finally{setBusy(false)}
 }
 const shortage=operation?Math.max(0,Number(operation.schedule_qty)-Number(operation.total_available_capacity_qty??operation.total_capacity_qty)):0
 return <><PageHeader title="Machine Capacity & Manpower" subtitle="Monthly part loading from the operation schedule, effective cycle time, machine calendar and operator requirement." actions={<button className="secondary" onClick={load} disabled={busy}>{busy?'Calculating…':'Recalculate'}</button>}/>
 {msg&&<div className={msg.toLowerCase().includes('saved')?'notice':'warning-box'}>{msg}</div>}
 <section className="panel capacity-scope"><div className="form-row"><label>Month<input type="date" value={month} onChange={e=>setMonth(e.target.value)}/></label><label>Product / Part<MultiSelect className="manual-search-select" value={pid?[pid]:[]} onChange={v=>setPid(v.at(-1)||'')} placeholder="Select Product" options={products.map(p=>({value:String(p.id),label:p.name}))}/></label><label>Operation<MultiSelect className="manual-search-select" value={opId?[opId]:[]} onChange={v=>setOpId(v.at(-1)||'')} placeholder="Select Operation" options={(plan?.operations||[]).map((o:any)=>({value:String(o.route_operation_id),label:`${o.sequence_no}. ${o.operation}`}))}/></label></div><p className="muted">Plant calendar: {plan?.plant||'—'} • Working days: {plan?.working_days??'—'} • Operation demand comes from Daily Requirements generated by the monthly schedule.</p></section>
 <section className="panel"><div className="panel-title"><div><h2>Monthly Machine Loading — All Products</h2><p>Consolidated physical-machine utilization from the latest saved allocation revision of every product / operation in the selected month.</p></div><button className="secondary" onClick={loadMachineLoading}>Refresh loading</button></div>
 {machineLoading&&<><div className="kpi-grid"><Kpi label="Active Machines" value={machineLoading.machine_count||0}/><Kpi label="Machines Allocated" value={machineLoading.allocated_machine_count||0}/><Kpi label="Overloaded Machines" value={machineLoading.overloaded_machine_count||0} tone={machineLoading.overloaded_machine_count?'bad':'good'}/><Kpi label="Near Capacity" value={machineLoading.near_capacity_machine_count||0} tone={machineLoading.near_capacity_machine_count?'warn':'neutral'}/><Kpi label="Underloaded" value={machineLoading.underloaded_machine_count||0} tone="neutral"/><Kpi label="Operator Equivalent" value={Number(machineLoading.required_operator_equivalent||0).toFixed(2)} sub="Concurrent monthly load equivalent"/><Kpi label="Operator Hours" value={num(machineLoading.operator_hours||0)} sub="Planned run-hours × manpower"/></div>
 {machineLoading?.areas?.length>0&&<div className="table-wrap"><table><thead><tr><th>Plant</th><th>Department</th><th>Machines</th><th>Allocated</th><th>Overloaded</th><th>Operator Eq.</th><th>Operator Hours</th></tr></thead><tbody>{machineLoading.areas.map((a:any)=><tr key={a.plant+'-'+a.department}><td>{a.plant}</td><td>{a.department}</td><td>{a.machine_count}</td><td>{a.allocated_machine_count}</td><td>{a.overloaded_machine_count}</td><td><b>{Number(a.required_operator_equivalent||0).toFixed(2)}</b></td><td>{num(a.operator_hours||0)}</td></tr>)}</tbody></table></div>}
 <div className="table-wrap"><table><thead><tr><th>Machine</th><th>Plant / Department</th><th>Allocated Load</th><th>Available Load</th><th>Operator Eq.</th><th>Operator Hours</th><th>Saved Allocations</th><th>Product / Operation Breakdown</th><th>Status</th></tr></thead><tbody>{(machineLoading.machines||[]).map((m:any)=><tr key={m.machine_id}><td><b>{m.machine_code}</b><br/><small>{m.machine_name}</small></td><td>{m.plant||'—'}{m.department?' / '+m.department:''}</td><td><b>{Number(m.allocated_load_percent||0).toFixed(1)}%</b></td><td>{Number(m.available_load_percent||0).toFixed(1)}%</td><td>{Number(m.required_operator_equivalent||0).toFixed(2)}</td><td>{num(m.operator_hours||0)}</td><td>{m.allocation_count||0}</td><td>{m.allocations?.length?m.allocations.map((a:any)=><div key={String(a.product_id)+'-'+String(a.route_operation_id)}><b>{a.product_code||a.product}</b> — {a.operation}: {num(a.allocated_qty)} pcs <small>({Number(a.load_percent||0).toFixed(1)}% load, CT {Number(a.planning_cycle_time_sec||0).toFixed(2)}s)</small></div>):<span className="muted">No saved allocation</span>}</td><td><Status value={m.status}/>{Number(m.overload_percent||0)>0&&<><br/><small>{Number(m.overload_percent).toFixed(1)}% over capacity</small></>}</td></tr>)}</tbody></table></div></>}
 </section>
 {operation&&<>
 <div className="kpi-grid"><Kpi label="Operation Schedule" value={num(operation.schedule_qty)}/><Kpi label="Available Capacity" value={num(operation.total_available_capacity_qty??operation.total_capacity_qty)} tone={shortage?'bad':'good'} sub={`Gross mapped ${num(operation.total_capacity_qty)}`}/><Kpi label="Capacity Shortage" value={num(shortage)} tone={shortage?'bad':'good'}/><Kpi label="Operators Required" value={liveOperators} tone="neutral" sub="For the allocation shown below"/><Kpi label="Estimated Run Cost" value={money(liveRunCost)} sub="Machine conversion cost"/></div>
 <section className="panel"><div className="panel-title"><div><h2>Part-to-machine monthly allocation</h2><p>{operation.allocation_source} allocation {operation.allocation_revision?`revision R${operation.allocation_revision}`:'preview'}; priority is used for Auto allocate.</p></div><button className="secondary" onClick={autoAllocate}>Auto allocate</button></div>
 <div className="table-wrap"><table><thead><tr><th>Priority</th><th>Machine</th><th>Cycle sec/pc</th><th>Gross capacity</th><th>Other load</th><th>Available capacity</th><th>Allocate qty</th><th>Current / total load</th><th>Operators/machine</th><th>Operators required</th><th>Cost/hour</th><th>Cost/piece</th><th>Planned cost</th><th>Readiness</th></tr></thead><tbody>{operation.machines.map((m:any)=>{const ownLoad=m.capacity_qty?Number(alloc[String(m.machine_id)]||0)/Number(m.capacity_qty)*100:0;const totalLoad=Number(m.other_allocated_load_percent||0)+ownLoad;return <tr key={m.machine_id}><td>{m.priority}</td><td><b>{m.machine_code}</b><br/><small>{m.machine_name}</small></td><td>{m.planning_cycle_time_sec?Number(m.planning_cycle_time_sec).toFixed(2):'—'}</td><td>{num(m.capacity_qty)}</td><td>{Number(m.other_allocated_load_percent||0).toFixed(1)}%</td><td><b>{num(m.available_capacity_qty??m.capacity_qty)}</b></td><td><input type="number" min="0" max={Math.floor(Number(m.available_capacity_qty??m.capacity_qty))} value={alloc[String(m.machine_id)]??'0'} onChange={e=>setAlloc({...alloc,[String(m.machine_id)]:e.target.value})}/></td><td>{m.capacity_qty?`${ownLoad.toFixed(1)}% / ${totalLoad.toFixed(1)}%`:'—'}</td><td>{m.operators_per_machine||'—'}</td><td>{m.capacity_qty?Math.ceil(Number(alloc[String(m.machine_id)]||0)/m.capacity_qty*m.operators_per_machine):0}</td><td>{money(m.estimated_hourly_cost)}</td><td>₹{Number(m.estimated_cost_per_piece||0).toFixed(2)}</td><td>{money(Number(alloc[String(m.machine_id)]||0)*Number(m.estimated_cost_per_piece||0))}{!m.cost_complete&&<><br/><small>{m.cost_missing.join(', ')}</small></>}</td><td>{m.complete?<><Status value={Number(m.available_capacity_qty??m.capacity_qty)>0?'Ready':'Full'}/>{Number(m.other_allocated_load_percent||0)>0&&<><br/><small>{Number(m.other_allocated_load_percent).toFixed(1)}% committed to other parts</small></>}</>:<><Status value="Blocked"/><br/><small>{m.missing.join(', ')}</small></>}</td></tr>})}</tbody></table></div>
 {!operation.machines.length&&<p className="warning-box">No effective machine mapping exists for this part and operation.</p>}
 {allocationOverCapacity&&<div className="warning-box">Allocation exceeds the remaining capacity of at least one machine. Reduce the quantity before saving.</div>}
 {allocationOverSchedule&&<div className="warning-box">Allocated quantity cannot exceed the monthly operation schedule.</div>}
 {!allocationOverCapacity&&!allocationOverSchedule&&allocated<Number(operation.schedule_qty)&&<div className="warning-box">Capacity shortage / unallocated schedule: {num(Number(operation.schedule_qty)-allocated)}. You can save this partial allocation as the approved monthly loading gap.</div>}
 <div className="allocation-footer"><span>Allocated <b>{num(allocated)}</b> / Schedule <b>{num(operation.schedule_qty)}</b> • Gap <b className={Math.abs(allocated-Number(operation.schedule_qty))<0.001?'pos':'neg'}>{num(Number(operation.schedule_qty)-allocated)}</b></span><label>Allocation reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||allocationOverCapacity||allocationOverSchedule||allocated<=0||!operation.machines.length} onClick={saveAllocation}>Save allocation revision</button></div></section>

 <section className="panel"><div className="panel-title"><div><h2>Machine / part capacity master setup</h2><p>Save each effective-dated master separately. Old values remain in history.</p></div></div>
 <div className="capacity-master-grid"><label>Machine<MultiSelect className="manual-search-select" value={setup.machine_id?[String(setup.machine_id)]:[]} onChange={v=>setSetup({...setup,machine_id:v.at(-1)||''})} placeholder="Select Machine" options={machines.map(m=>({value:String(m.id),label:`${m.code} — ${m.name}`}))}/></label><label>Effective from<input type="date" value={setup.effective_from} onChange={e=>setSetup({...setup,effective_from:e.target.value})}/></label><label>Mapping priority<input type="number" min="1" value={setup.priority} onChange={e=>setSetup({...setup,priority:e.target.value})}/></label>
 <label>Ideal cycle sec/pc<input type="number" step="0.001" value={setup.ideal_cycle_time_sec} onChange={e=>setSetup({...setup,ideal_cycle_time_sec:e.target.value})}/></label><label>Standard cycle sec/pc<input type="number" step="0.001" value={setup.standard_cycle_time_sec} onChange={e=>setSetup({...setup,standard_cycle_time_sec:e.target.value})}/></label><label>Pieces per cycle<input type="number" min="1" value={setup.pieces_per_cycle} onChange={e=>setSetup({...setup,pieces_per_cycle:e.target.value})}/></label>
 <label>Operators per running machine<input type="number" step="0.001" min="0.001" value={setup.operators_per_machine} onChange={e=>setSetup({...setup,operators_per_machine:e.target.value})}/></label>
 <label>Shifts/day<input type="number" min="1" max="6" value={setup.shifts_per_day} onChange={e=>setSetup({...setup,shifts_per_day:e.target.value})}/></label><label>Shift minutes<input type="number" value={setup.shift_minutes} onChange={e=>setSetup({...setup,shift_minutes:e.target.value})}/></label><label>Break minutes/shift<input type="number" value={setup.planned_break_minutes} onChange={e=>setSetup({...setup,planned_break_minutes:e.target.value})}/></label><label>Planning efficiency %<input type="number" min="1" max="100" value={setup.planning_efficiency_percent} onChange={e=>setSetup({...setup,planning_efficiency_percent:e.target.value})}/></label>
 <label className="span-all">Change reason<input value={setup.reason} onChange={e=>setSetup({...setup,reason:e.target.value})}/></label></div>
 <div className="button-row"><button onClick={()=>saveMaster('map')}>Save part mapping</button><button disabled={!setup.ideal_cycle_time_sec} onClick={()=>saveMaster('cycle')}>Save cycle-time revision</button><button disabled={!setup.operators_per_machine} onClick={()=>saveMaster('operator')}>Save operator revision</button><button onClick={()=>saveMaster('capacity')}>Save machine capacity revision</button></div></section>

 <section className="panel"><div className="panel-title"><h2>Cycle time and operator change history</h2><span>Selected operation / machine</span></div><div className="table-wrap"><table><thead><tr><th>Master</th><th>Machine</th><th>Effective</th><th>Value</th><th>Reason</th><th>Changed by</th></tr></thead><tbody>
 {(history.cycle_times||[]).map((x:any)=><tr key={`c${x.id}`}><td>Cycle time</td><td>{x.machine}</td><td>{x.effective_from} → {x.effective_to||'Current'}</td><td>Ideal {x.ideal_cycle_time_sec}s • Standard {x.standard_cycle_time_sec??'—'}s • {x.pieces_per_cycle} pc/cycle</td><td>{x.reason||'—'}</td><td>{x.entered_by||'Legacy data'}</td></tr>)}
 {(history.operator_requirements||[]).map((x:any)=><tr key={`o${x.id}`}><td>Operator requirement</td><td>{x.machine}</td><td>{x.effective_from} → {x.effective_to||'Current'}</td><td>{x.operators_per_machine} operator/machine</td><td>{x.reason}</td><td>{x.entered_by||'Legacy data'}</td></tr>)}
 {(history.machine_settings||[]).map((x:any)=><tr key={`s${x.id}`}><td>Capacity pattern</td><td>{x.machine}</td><td>{x.effective_from} → {x.effective_to||'Current'}</td><td>{x.shifts_per_day} shifts × {x.shift_minutes-x.planned_break_minutes} net min • {(x.planning_efficiency*100).toFixed(1)}%</td><td>{x.reason}</td><td>{x.entered_by||'Legacy data'}</td></tr>)}
 {(history.machine_maps||[]).map((x:any)=><tr key={`m${x.id}`}><td>Part mapping</td><td>{x.machine}</td><td>{x.effective_from} → {x.effective_to||'Current'}</td><td>Priority {x.priority}</td><td>{x.reason||'—'}</td><td>{x.entered_by||'Legacy data'}</td></tr>)}
 </tbody></table></div></section>

 <section className="panel"><div className="panel-title"><h2>Monthly allocation history</h2><span>Append-only revisions</span></div><div className="table-wrap"><table><thead><tr><th>Revision</th><th>Machine</th><th>Allocated</th><th>Schedule snapshot</th><th>Capacity snapshot</th><th>Cycle</th><th>Operator</th><th>Cost/hour</th><th>Cost/piece</th><th>Reason</th><th>Changed by</th></tr></thead><tbody>{allocationHistory.map((x:any)=><tr key={x.id}><td>R{x.revision_no}</td><td>{x.machine}</td><td>{num(x.allocated_qty)}</td><td>{num(x.schedule_qty)}</td><td>{num(x.capacity_qty)}</td><td>{x.cycle_time_sec}s</td><td>{x.operators_per_machine}</td><td>{x.estimated_hourly_cost==null?'—':money(x.estimated_hourly_cost)}</td><td>{x.estimated_cost_per_piece==null?'—':`₹${Number(x.estimated_cost_per_piece).toFixed(2)}`}</td><td>{x.reason}</td><td>{x.entered_by||'Legacy data'}</td></tr>)}</tbody></table></div></section>
 </>}
 {!busy&&plan&&!plan.operations.length&&<div className="empty">No operation-level monthly schedule exists. Load or recalculate the monthly schedule first.</div>}
 </>
}
