import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../api'
import { Kpi, PageHeader, Status, money, num } from '../components/UI'

const monthNow=()=>new Date().toISOString().slice(0,7)+'-01'
const today=()=>new Date().toISOString().slice(0,10)

export default function CapacityPlanning(){
 const [params]=useSearchParams()
 const [products,setProducts]=useState<any[]>([]);const [machines,setMachines]=useState<any[]>([])
 const [pid,setPid]=useState('');const [month,setMonth]=useState(monthNow());const [plan,setPlan]=useState<any>(null);const [opId,setOpId]=useState('')
 const [alloc,setAlloc]=useState<Record<string,string>>({});const [history,setHistory]=useState<any>({});const [allocationHistory,setAllocationHistory]=useState<any[]>([])
 const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');const [reason,setReason]=useState('Monthly machine allocation approved')
 const [setup,setSetup]=useState<any>({machine_id:'',effective_from:today(),priority:1,ideal_cycle_time_sec:'',standard_cycle_time_sec:'',pieces_per_cycle:1,operators_per_machine:'',shifts_per_day:3,shift_minutes:480,planned_break_minutes:30,planning_efficiency_percent:85,reason:'Approved capacity master revision'})
 useEffect(()=>{Promise.all([api('/masters/products'),api('/masters/machines')]).then(([p,m]:any)=>{setProducts(p);setMachines(m);const requested=params.get('product_id');if(requested&&p.some((x:any)=>String(x.id)===requested))setPid(requested);else if(p[0])setPid(String(p[0].id));if(m[0])setSetup((x:any)=>({...x,machine_id:String(m[0].id)}))})},[])
 async function load(){if(!pid)return;setBusy(true);setMsg('');try{const p:any=await api(`/capacity/plan?product_id=${pid}&month=${month}`);setPlan(p);const next=p.operations.some((x:any)=>String(x.route_operation_id)===opId)?opId:String(p.operations[0]?.route_operation_id||'');setOpId(next)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[pid,month])
 const operation=useMemo(()=>plan?.operations?.find((x:any)=>String(x.route_operation_id)===opId),[plan,opId])
 useEffect(()=>{if(!operation)return;const x:Record<string,string>={};operation.machines.forEach((m:any)=>x[String(m.machine_id)]=String(m.allocation_qty));setAlloc(x);loadHistory()},[operation?.route_operation_id,operation?.allocation_revision,setup.machine_id])
 async function loadHistory(){if(!opId)return;const q=`route_operation_id=${opId}${setup.machine_id?`&machine_id=${setup.machine_id}`:''}`;const [h,a]:any=await Promise.all([api(`/capacity/master-history?${q}`),api(`/capacity/allocations/history?product_id=${pid}&route_operation_id=${opId}&month=${month}`)]);setHistory(h);setAllocationHistory(a)}
 function autoAllocate(){if(!operation)return;let remaining=Math.round(Number(operation.schedule_qty));const x:Record<string,string>={};const usable=[...operation.machines].filter((m:any)=>m.complete).sort((a:any,b:any)=>a.priority-b.priority||a.machine_code.localeCompare(b.machine_code));operation.machines.forEach((m:any)=>x[String(m.machine_id)]='0');usable.forEach((m:any)=>{const q=Math.min(remaining,Math.floor(m.capacity_qty));x[String(m.machine_id)]=String(q);remaining-=q});if(remaining>0&&usable[0])x[String(usable[0].machine_id)]=String(Number(x[String(usable[0].machine_id)])+remaining);setAlloc(x)}
 const allocated=operation?.machines?.reduce((s:number,m:any)=>s+Number(alloc[String(m.machine_id)]||0),0)||0
 const liveOperators=operation?Math.ceil(operation.machines.reduce((s:number,m:any)=>s+(m.capacity_qty?Number(alloc[String(m.machine_id)]||0)/m.capacity_qty*m.operators_per_machine:0),0)):0
 const liveRunCost=operation?operation.machines.reduce((s:number,m:any)=>s+Number(alloc[String(m.machine_id)]||0)*Number(m.estimated_cost_per_piece||0),0):0
 async function saveAllocation(){if(!operation)return;setBusy(true);try{const r:any=await api('/capacity/allocations',{method:'POST',body:JSON.stringify({product_id:Number(pid),route_operation_id:Number(opId),month,effective_from:month,reason,allocations:operation.machines.map((m:any)=>({machine_id:m.machine_id,allocated_qty:Number(alloc[String(m.machine_id)]||0)}))})});setMsg(`Machine allocation revision R${r.revision_no} saved for ${num(r.schedule_qty)} pieces.`);await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function saveMaster(kind:'map'|'cycle'|'operator'|'capacity'){
  if(!opId||!setup.machine_id)return;setBusy(true);setMsg('')
  try{
   if(kind==='map')await api('/masters/machine-maps',{method:'POST',body:JSON.stringify({route_operation_id:Number(opId),machine_id:Number(setup.machine_id),effective_from:setup.effective_from,priority:Number(setup.priority),reason:setup.reason})})
   if(kind==='cycle')await api('/masters/cycle-times',{method:'POST',body:JSON.stringify({route_operation_id:Number(opId),machine_id:Number(setup.machine_id),effective_from:setup.effective_from,ideal_cycle_time_sec:Number(setup.ideal_cycle_time_sec),standard_cycle_time_sec:setup.standard_cycle_time_sec===''?null:Number(setup.standard_cycle_time_sec),pieces_per_cycle:Number(setup.pieces_per_cycle),reason:setup.reason})})
   if(kind==='operator')await api('/capacity/operator-requirements',{method:'POST',body:JSON.stringify({route_operation_id:Number(opId),machine_id:Number(setup.machine_id),effective_from:setup.effective_from,operators_per_machine:Number(setup.operators_per_machine),reason:setup.reason})})
   if(kind==='capacity')await api('/capacity/machine-settings',{method:'POST',body:JSON.stringify({machine_id:Number(setup.machine_id),effective_from:setup.effective_from,shifts_per_day:Number(setup.shifts_per_day),shift_minutes:Number(setup.shift_minutes),planned_break_minutes:Number(setup.planned_break_minutes),planning_efficiency:Number(setup.planning_efficiency_percent)/100,reason:setup.reason})})
   setMsg(`${kind} revision saved from ${setup.effective_from}. Earlier effective history is retained.`);await load();await loadHistory()
  }catch(e:any){setMsg(e.message)}finally{setBusy(false)}
 }
 const shortage=operation?Math.max(0,Number(operation.schedule_qty)-Number(operation.total_capacity_qty)):0
 return <><PageHeader title="Machine Capacity & Manpower" subtitle="Monthly part loading from the operation schedule, effective cycle time, machine calendar and operator requirement." actions={<button className="secondary" onClick={load} disabled={busy}>{busy?'Calculating…':'Recalculate'}</button>}/>
 {msg&&<div className={msg.toLowerCase().includes('saved')?'notice':'warning-box'}>{msg}</div>}
 <section className="panel capacity-scope"><div className="form-row"><label>Month<input type="date" value={month} onChange={e=>setMonth(e.target.value)}/></label><label>Product / Part<select value={pid} onChange={e=>setPid(e.target.value)}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Operation<select value={opId} onChange={e=>setOpId(e.target.value)}>{(plan?.operations||[]).map((o:any)=><option key={o.route_operation_id} value={o.route_operation_id}>{o.sequence_no}. {o.operation}</option>)}</select></label></div><p className="muted">Plant calendar: {plan?.plant||'—'} • Working days: {plan?.working_days??'—'} • Operation demand comes from Daily Requirements generated by the monthly schedule.</p></section>
 {operation&&<>
 <div className="kpi-grid"><Kpi label="Operation Schedule" value={num(operation.schedule_qty)}/><Kpi label="Mapped Capacity" value={num(operation.total_capacity_qty)} tone={shortage?'bad':'good'}/><Kpi label="Capacity Shortage" value={num(shortage)} tone={shortage?'bad':'good'}/><Kpi label="Operators Required" value={liveOperators} tone="neutral" sub="For the allocation shown below"/><Kpi label="Estimated Run Cost" value={money(liveRunCost)} sub="Machine conversion cost"/></div>
 <section className="panel"><div className="panel-title"><div><h2>Part-to-machine monthly allocation</h2><p>{operation.allocation_source} allocation {operation.allocation_revision?`revision R${operation.allocation_revision}`:'preview'}; priority is used for Auto allocate.</p></div><button className="secondary" onClick={autoAllocate}>Auto allocate</button></div>
 <div className="table-wrap"><table><thead><tr><th>Priority</th><th>Machine</th><th>Cycle sec/pc</th><th>Monthly capacity</th><th>Allocate qty</th><th>Load</th><th>Operators/machine</th><th>Operators required</th><th>Cost/hour</th><th>Cost/piece</th><th>Planned cost</th><th>Readiness</th></tr></thead><tbody>{operation.machines.map((m:any)=><tr key={m.machine_id}><td>{m.priority}</td><td><b>{m.machine_code}</b><br/><small>{m.machine_name}</small></td><td>{m.planning_cycle_time_sec?Number(m.planning_cycle_time_sec).toFixed(2):'—'}</td><td>{num(m.capacity_qty)}</td><td><input type="number" min="0" value={alloc[String(m.machine_id)]??'0'} onChange={e=>setAlloc({...alloc,[String(m.machine_id)]:e.target.value})}/></td><td>{m.capacity_qty?`${(Number(alloc[String(m.machine_id)]||0)/m.capacity_qty*100).toFixed(1)}%`:'—'}</td><td>{m.operators_per_machine||'—'}</td><td>{m.capacity_qty?Math.ceil(Number(alloc[String(m.machine_id)]||0)/m.capacity_qty*m.operators_per_machine):0}</td><td>{money(m.estimated_hourly_cost)}</td><td>₹{Number(m.estimated_cost_per_piece||0).toFixed(2)}</td><td>{money(Number(alloc[String(m.machine_id)]||0)*Number(m.estimated_cost_per_piece||0))}{!m.cost_complete&&<><br/><small>{m.cost_missing.join(', ')}</small></>}</td><td>{m.complete?<Status value="Ready"/>:<><Status value="Blocked"/><br/><small>{m.missing.join(', ')}</small></>}</td></tr>)}</tbody></table></div>
 {!operation.machines.length&&<p className="warning-box">No effective machine mapping exists for this part and operation.</p>}
 <div className="allocation-footer"><span>Allocated <b>{num(allocated)}</b> / Schedule <b>{num(operation.schedule_qty)}</b> • Gap <b className={allocated===Number(operation.schedule_qty)?'pos':'neg'}>{num(Number(operation.schedule_qty)-allocated)}</b></span><label>Allocation reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||allocated!==Number(operation.schedule_qty)||!operation.machines.length} onClick={saveAllocation}>Save allocation revision</button></div></section>

 <section className="panel"><div className="panel-title"><div><h2>Machine / part capacity master setup</h2><p>Save each effective-dated master separately. Old values remain in history.</p></div></div>
 <div className="capacity-master-grid"><label>Machine<select value={setup.machine_id} onChange={e=>setSetup({...setup,machine_id:e.target.value})}>{machines.map(m=><option key={m.id} value={m.id}>{m.code} — {m.name}</option>)}</select></label><label>Effective from<input type="date" value={setup.effective_from} onChange={e=>setSetup({...setup,effective_from:e.target.value})}/></label><label>Mapping priority<input type="number" min="1" value={setup.priority} onChange={e=>setSetup({...setup,priority:e.target.value})}/></label>
 <label>Ideal cycle sec/pc<input type="number" step="0.001" value={setup.ideal_cycle_time_sec} onChange={e=>setSetup({...setup,ideal_cycle_time_sec:e.target.value})}/></label><label>Standard cycle sec/pc<input type="number" step="0.001" value={setup.standard_cycle_time_sec} onChange={e=>setSetup({...setup,standard_cycle_time_sec:e.target.value})}/></label><label>Pieces per cycle<input type="number" min="1" value={setup.pieces_per_cycle} onChange={e=>setSetup({...setup,pieces_per_cycle:e.target.value})}/></label>
 <label>Operators per running machine<input type="number" step="0.001" min="0.001" value={setup.operators_per_machine} onChange={e=>setSetup({...setup,operators_per_machine:e.target.value})}/></label>
 <label>Shifts/day<input type="number" min="1" max="6" value={setup.shifts_per_day} onChange={e=>setSetup({...setup,shifts_per_day:e.target.value})}/></label><label>Shift minutes<input type="number" value={setup.shift_minutes} onChange={e=>setSetup({...setup,shift_minutes:e.target.value})}/></label><label>Break minutes/shift<input type="number" value={setup.planned_break_minutes} onChange={e=>setSetup({...setup,planned_break_minutes:e.target.value})}/></label><label>Planning efficiency %<input type="number" min="1" max="100" value={setup.planning_efficiency_percent} onChange={e=>setSetup({...setup,planning_efficiency_percent:e.target.value})}/></label>
 <label className="span-all">Change reason<input value={setup.reason} onChange={e=>setSetup({...setup,reason:e.target.value})}/></label></div>
 <div className="button-row"><button onClick={()=>saveMaster('map')}>Save part mapping</button><button disabled={!setup.ideal_cycle_time_sec} onClick={()=>saveMaster('cycle')}>Save cycle-time revision</button><button disabled={!setup.operators_per_machine} onClick={()=>saveMaster('operator')}>Save operator revision</button><button onClick={()=>saveMaster('capacity')}>Save machine capacity revision</button></div></section>

 <section className="panel"><div className="panel-title"><h2>Cycle time and operator change history</h2><span>Selected operation / machine</span></div><div className="table-wrap"><table><thead><tr><th>Master</th><th>Machine</th><th>Effective</th><th>Value</th><th>Reason</th><th>Changed by</th></tr></thead><tbody>
 {(history.cycle_times||[]).map((x:any)=><tr key={`c${x.id}`}><td>Cycle time</td><td>{x.machine}</td><td>{x.effective_from} → {x.effective_to||'Current'}</td><td>Ideal {x.ideal_cycle_time_sec}s • Standard {x.standard_cycle_time_sec??'—'}s • {x.pieces_per_cycle} pc/cycle</td><td>{x.reason||'—'}</td><td>{x.entered_by||'Legacy data'}</td></tr>)}
 {(history.operator_requirements||[]).map((x:any)=><tr key={`o${x.id}`}><td>Operator requirement</td><td>{x.machine}</td><td>{x.effective_from} → {x.effective_to||'Current'}</td><td>{x.operators_per_machine} operator/machine</td><td>{x.reason}</td><td>{x.entered_by||'Legacy data'}</td></tr>)}
 {(history.machine_settings||[]).map((x:any)=><tr key={`s${x.id}`}><td>Capacity pattern</td><td>{x.machine}</td><td>{x.effective_from} → {x.effective_to||'Current'}</td><td>{x.shifts_per_day} shifts × {x.shift_minutes-x.planned_break_minutes} net min • {(x.planning_efficiency*100).toFixed(1)}%</td><td>{x.reason}</td><td>{x.entered_by||'Legacy data'}</td></tr>)}
 {(history.machine_maps||[]).map((x:any)=><tr key={`m${x.id}`}><td>Part mapping</td><td>{x.machine}</td><td>{x.effective_from} → {x.effective_to||'Current'}</td><td>Priority {x.priority}</td><td>{x.reason||'—'}</td><td>{x.entered_by||'Legacy data'}</td></tr>)}
 </tbody></table></div></section>

 <section className="panel"><div className="panel-title"><h2>Monthly allocation history</h2><span>Append-only revisions</span></div><div className="table-wrap"><table><thead><tr><th>Revision</th><th>Machine</th><th>Allocated</th><th>Schedule snapshot</th><th>Capacity snapshot</th><th>Cycle</th><th>Operator</th><th>Cost/hour</th><th>Cost/piece</th><th>Reason</th><th>Changed by</th></tr></thead><tbody>{allocationHistory.map((x:any)=><tr key={x.id}><td>R{x.revision_no}</td><td>{x.machine}</td><td>{num(x.allocated_qty)}</td><td>{num(x.schedule_qty)}</td><td>{num(x.capacity_qty)}</td><td>{x.cycle_time_sec}s</td><td>{x.operators_per_machine}</td><td>{x.estimated_hourly_cost==null?'—':money(x.estimated_hourly_cost)}</td><td>{x.estimated_cost_per_piece==null?'—':`₹${Number(x.estimated_cost_per_piece).toFixed(2)}`}</td><td>{x.reason}</td><td>{x.entered_by||'Legacy data'}</td></tr>)}</tbody></table></div></section>
 </>}
 {!busy&&plan&&!plan.operations.length&&<div className="empty">No operation-level monthly schedule exists. Load or recalculate the monthly schedule first.</div>}
 </>
}
