import { useEffect, useState } from 'react'
import { api, downloadApi } from '../api'
import { MultiSelect } from '../components/MultiSelect'
import { PageHeader, Status } from '../components/UI'

const today=()=>new Date().toISOString().slice(0,10)

export default function DailyMeeting(){
 const [date,setDate]=useState(today()); const [review,setReview]=useState<any>(null); const [mom,setMom]=useState<any>(null)
 const [users,setUsers]=useState<any[]>([]); const [participants,setParticipants]=useState(''); const [comments,setComments]=useState('')
 const [err,setErr]=useState(''); const [message,setMessage]=useState('')
 const [form,setForm]=useState<any>({category:'Production',discussion_point:'',action_required:true,action_description:'',owner_id:'',due_at:'',priority:'HIGH'})
 async function load(r:any){if(!r){setMom(null);return}setMom(await api(`/reviews/${r.id}/mom`))}
 async function find(){try{setErr('');const r:any=await api(`/reviews/active?review_date=${date}`);setReview(r);if(r){setParticipants(r.participants||'');setComments(r.comments||'');await load(r)}else setMom(null)}catch(e:any){setErr(e.message)}}
 useEffect(()=>{api('/masters/users').then((x:any)=>setUsers(x)).catch((e:any)=>setErr(e.message));find()},[])
 useEffect(()=>{find()},[date])
 async function start(){try{setErr('');const r:any=await api('/reviews',{method:'POST',body:JSON.stringify({review_date:date,participants:participants||null,comments:comments||null})});setReview(r);await load(r);setMessage(r.existing?'Existing meeting resumed.':'Daily Review meeting started.')}catch(e:any){setErr(e.message)}}
 async function addPoint(e:React.FormEvent){e.preventDefault();if(!review)return;try{setErr('');await api(`/reviews/${review.id}/points`,{method:'POST',body:JSON.stringify({...form,owner_id:form.owner_id?Number(form.owner_id):null,due_at:form.due_at?new Date(form.due_at).toISOString():null})});setForm((f:any)=>({...f,discussion_point:'',action_description:''}));await load(review);setMessage('MOM point added.')}catch(e:any){setErr(e.message)}}
 async function updateAction(a:any,status:string){const comment=prompt('Follow-up / closure remark');if(comment===null)return;try{await api(`/actions/${a.id}`,{method:'PATCH',body:JSON.stringify({status,comment:comment||`Status changed to ${status}`,closure_remark:status==='CLOSED'?(comment||'Closed'):null})});await load(review)}catch(e:any){setErr(e.message)}}
 async function escalate(a:any){if(!confirm(`Escalate ${a.action_no} to Why-Why analysis?`))return;try{await api(`/reviews/actions/${a.id}/escalate-whywhy`,{method:'POST'});await load(review);setMessage(`${a.action_no} escalated to Why-Why.`)}catch(e:any){setErr(e.message)}}
 async function close(){if(!review)return;try{const r:any=await api(`/reviews/${review.id}/close`,{method:'PATCH',body:JSON.stringify({comments:comments||null})});setReview(r);await load(r);setMessage('Meeting closed. MOM remains available for download.')}catch(e:any){setErr(e.message)}}
 return <><PageHeader title="Daily Review Meeting" subtitle="Record MOM points, assign simple actions and carry pending actions forward. Why-Why is optional escalation only."/>
 {err&&<div className="error">{err}</div>}{message&&<div className="notice">{message}</div>}
 <section className="panel"><div className="form-row"><label>Meeting date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Participants<input value={participants} onChange={e=>setParticipants(e.target.value)} placeholder="Names / departments"/></label><label>Meeting remarks<input value={comments} onChange={e=>setComments(e.target.value)}/></label>{!review?<button onClick={start}>Start Meeting</button>:<><button className="secondary" onClick={()=>downloadApi(`/reviews/${review.id}/pdf`,`${mom?.mom_no||'MOM'}.pdf`)}>Download MOM PDF</button><button className="secondary" onClick={()=>downloadApi(`/reviews/${review.id}/xlsx`,`${mom?.mom_no||'MOM'}.xlsx`)}>Download Excel</button>{!review.ended_at&&<button onClick={close}>Close Meeting</button>}</>}</div>
 {mom&&<div className="data-note"><b>{mom.mom_no}</b> • {review?.ended_at?'Closed':'Meeting active'}</div>}</section>
 {review&&!review.ended_at&&<section className="panel"><h2>Add discussion / MOM point</h2><form onSubmit={addPoint}><div className="form-row"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Production</option><option>Quality</option><option>Delivery</option><option>Maintenance</option><option>Capacity</option><option>Customer</option><option>Safety</option><option>Cost</option><option>Other</option></select></label><label>Action Required<select value={form.action_required?'YES':'NO'} onChange={e=>setForm({...form,action_required:e.target.value==='YES'})}><option>YES</option><option>NO</option></select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label></div><label>Discussion / MOM Point<textarea required value={form.discussion_point} onChange={e=>setForm({...form,discussion_point:e.target.value})}/></label>{form.action_required&&<><label>Action Required<textarea required value={form.action_description} onChange={e=>setForm({...form,action_description:e.target.value})}/></label><div className="form-row"><label>Owner<MultiSelect className="manual-search-select" value={form.owner_id?[String(form.owner_id)]:[]} onChange={v=>setForm({...form,owner_id:v.at(-1)||''})} placeholder="Unassigned" options={users.map(u=>({value:String(u.id),label:u.full_name}))}/></label><label>Target Date<input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label></div></>}<button>Add MOM Point</button></form></section>}
 {mom?.previous_pending_actions?.length>0&&<section className="panel"><div className="panel-title"><h2>Previous Pending Actions</h2><span>Automatic carry-forward</span></div><div className="table-wrap"><table><thead><tr><th>Action</th><th>Owner</th><th>Target</th><th>Age</th><th>Status</th><th>Follow-up</th></tr></thead><tbody>{mom.previous_pending_actions.map((a:any)=><tr key={a.id} className={a.overdue_days?'row-overdue':''}><td><b>{a.action_no}</b><br/><small>{a.description}</small></td><td>{a.owner||'Unassigned'}</td><td>{String(a.due_at||'').slice(0,10)||'—'}{a.overdue_days>0&&<><br/><small>{a.overdue_days}d overdue</small></>}</td><td>{a.age_days}d</td><td><Status value={a.status}/></td><td><select value={a.status} onChange={e=>updateAction(a,e.target.value)}><option>OPEN</option><option>IN_PROGRESS</option><option>BLOCKED</option><option>CLOSED</option></select>{!a.requires_whywhy&&<button className="secondary small" type="button" onClick={()=>escalate(a)}>Escalate to Why-Why</button>}</td></tr>)}</tbody></table></div></section>}
 {mom&&<section className="panel"><div className="panel-title"><h2>Today's MOM Points</h2><span>{mom.points.length} point(s)</span></div><div className="table-wrap"><table><thead><tr><th>Sr.</th><th>Category</th><th>Discussion</th><th>Action / Owner</th><th>Target</th><th>Status</th><th>Follow-up</th></tr></thead><tbody>{mom.points.map((p:any)=><tr key={p.id}><td>{p.sequence_no}</td><td>{p.category||'—'}</td><td>{p.discussion_point}</td><td>{p.action?<><b>{p.action.action_no}</b><br/>{p.action.description}<br/><small>{p.action.owner||'Unassigned'}</small></>:'No action'}</td><td>{p.action?String(p.action.due_at||'').slice(0,10)||'—':'—'}</td><td>{p.action?<Status value={p.action.status}/>:<Status value="INFO"/>}</td><td>{p.action&&<><select value={p.action.status} onChange={e=>updateAction(p.action,e.target.value)}><option>OPEN</option><option>IN_PROGRESS</option><option>BLOCKED</option><option>CLOSED</option></select>{!p.action.requires_whywhy&&<button className="secondary small" type="button" onClick={()=>escalate(p.action)}>Escalate to Why-Why</button>}</>}</td></tr>)}</tbody></table></div></section>}
 </>}
