import { useEffect, useState } from 'react'
import { api } from '../api'
import { PageHeader } from '../components/UI'
import { MultiSelect } from '../components/MultiSelect'
export default function Governance(){
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7)),[reason,setReason]=useState(''),[rows,setRows]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[user,setUser]=useState(''),[message,setMessage]=useState('')
 async function load(){try{setRows(await api('/governance/months'));setAudit(await api(`/governance/audit?month=${month}-01`))}catch(e:any){setMessage(e.message)}}
 useEffect(()=>{load();api('/masters/users').then((x:any)=>setUsers(x)).catch(()=>{})},[month])
 async function command(c:string){try{await api(`/governance/months/${c}`,{method:'POST',body:JSON.stringify({month:month+'-01',reason})});setMessage(`Month ${c} completed`);load()}catch(e:any){setMessage(e.message)}}
 async function grant(){try{const r=await api('/governance/corrections',{method:'POST',body:JSON.stringify({month:month+'-01',reason,user_id:Number(user)})});setMessage(`Correction authorization #${r.correction_id}, valid until ${r.expires_at} UTC. Enter this number in the correction field before the edit.`);load()}catch(e:any){setMessage(e.message)}}
 return <><PageHeader title="Month Close / Historical Corrections" subtitle="Closing protects MIS, planning, prices, quality, OEE and WIP. Every change is retained in the audit trail."/><section className="panel"><label>Month<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><button onClick={()=>command('close')}>Close month</button> <button onClick={()=>command('reopen')}>Reopen month</button><label>Authorize correction for<>{users.length>0?<MultiSelect className="manual-search-select" value={user?[String(user)]:[]} onChange={v=>setUser(v.at(-1)||'')} placeholder="Select User" options={users.map(u=>({value:String(u.id),label:u.full_name}))}/>:<input type="number" min="1" value={user} onChange={e=>setUser(e.target.value)} placeholder="Known user ID"/>}</></label><button disabled={!user} onClick={grant}>Authorize one correction request</button>{message&&<p className="notice">{message}</p>}</section><section className="panel"><h2>Month states</h2><table><thead><tr><th>Month</th><th>Status</th><th>Reason</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.month}</td><td>{r.status}</td><td>{r.remark}</td></tr>)}</tbody></table></section><section className="panel"><h2>Audit trail</h2><table><thead><tr><th>Time (UTC)</th><th>Event</th><th>Entity</th><th>User</th><th>Reason</th><th>Evidence</th></tr></thead><tbody>{audit.map(r=><tr key={r.id}><td>{r.created_at}</td><td>{r.event}</td><td>{r.entity} #{r.entity_id}</td><td>{r.actor_id}</td><td>{r.reason}</td><td><details><summary>Before / After</summary><pre>{r.before_json}</pre><pre>{r.after_json}</pre></details></td></tr>)}</tbody></table></section></>
}
