import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { api } from '../api'
import { ScopeFilters, ScopeValues, appendScope } from '../components/ScopeFilters'
import { PageHeader } from '../components/UI'
import { ValueTrendChart } from '../components/Charts'
function Records({rows}:{rows:any[]}){
 if(!rows?.length)return <p>No matching records.</p>
 const keys=Array.from(new Set(rows.flatMap(r=>Object.keys(r)))).filter(k=>!['password_hash','token_version'].includes(k))
 return <div className="table-wrap"><table><thead><tr>{keys.map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{keys.map(k=><td key={k}>{typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k]??'—')}</td>)}</tr>)}</tbody></table></div>
}
export default function Insights(){
 const [params]=useSearchParams(),[mode,setMode]=useState(params.get('kind')||'exceptions'),[from,setFrom]=useState(params.get('from_date')||new Date().toISOString().slice(0,10)),[to,setTo]=useState(params.get('to_date')||new Date().toISOString().slice(0,10))
 const [scope,setScope]=useState<ScopeValues>({plant:params.get('plant')?.split(',')||[],productGroup:params.get('product_group')?.split(',')||[],customerId:params.get('customer_id')?.split(',')||[],productId:params.get('product_id')?.split(',')||[]})
 const [options,setOptions]=useState<any>({}),[products,setProducts]=useState<any[]>([]),[data,setData]=useState<any>(null),[error,setError]=useState(''),[target,setTarget]=useState({compliance:'0.9',ppm:'1000',oee:'0.85',loss:'60'})
 useEffect(()=>{Promise.all([api('/masters/filter-options'),api('/masters/products')]).then(([o,p])=>{setOptions(o);setProducts(p)}).catch(e=>setError(e.message))},[])
 async function load(){try{const q=appendScope(new URLSearchParams({as_of:to,from_date:from,to_date:to}),scope);for(const k of ['machine_id','phenomenon_id','operation_id','shift'])if(params.get(k))q.set(k,params.get(k)!);if(mode==='exceptions'){q.set('compliance_target',target.compliance);q.set('ppm_target',target.ppm);q.set('oee_target',target.oee);q.set('major_loss_min',target.loss)}setData(await api(`/insights/${['compliance','ppm','oee'].includes(mode)?'drilldown/'+mode:mode}?${q}`));setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{load()},[mode,from,to,scope])
 const rows=data?.exceptions||data?.issues||data?.actions||[]
 const bars=Object.entries(data?.counts||{}).map(([label,value])=>({label,value}))
 function drill(r:any){if(mode==='data-quality')return r.kind==='machine_pm_overdue'?'/machine-master':['machine_mapping_missing','cycle_time_missing','operator_requirement_missing','machine_capacity_setting_missing'].includes(r.kind)?`/capacity${r.product_id?`?product_id=${r.product_id}`:''}`:'/masters';if(mode==='escalation')return '/actions';const kind=['low_compliance','schedule_risk'].includes(r.kind)?'compliance':r.kind==='high_ppm'?'ppm':['low_oee','major_loss'].includes(r.kind)?'oee':r.kind==='data_quality'?'data-quality':'escalation';return `/insights?${new URLSearchParams({kind,from_date:from,to_date:to,...(r.product_id?{product_id:String(r.product_id)}:{})})}`}
 return <><PageHeader title="Management Exceptions / Data Quality" subtitle="Select an exception or chart to open the supporting records. Thresholds are adjustable for each review."/><section className="panel"><div className="filters"><label>View<select value={mode} onChange={e=>setMode(e.target.value)}>{[['exceptions','Management exceptions'],['data-quality','Data quality'],['escalation','Action escalation / reminders'],['compliance','Compliance details'],['ppm','PPM / phenomenon details'],['oee','Machine / loss details']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To / Review date<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><ScopeFilters value={scope} onChange={setScope} options={options} products={products}/></div>{mode==='exceptions'&&<div className="filters">{Object.keys(target).map(k=><label key={k}>{k} target<input type="number" min="0" step="0.01" value={(target as any)[k]} onChange={e=>setTarget({...target,[k]:e.target.value})}/></label>)}</div>}<button onClick={load}>Refresh</button></section>{error&&<p className="error">{error}</p>}{bars.length>0&&<section className="panel"><h2>Exception counts</h2><ValueTrendChart rows={bars} label="Conditions" onSelect={(r:any)=>{const matching=rows.find((x:any)=>x.kind===r.label);if(matching)location.href=drill(matching)}}/></section>}{data?.production?.length>0&&<section className="panel"><h2>Machine OEE</h2><ValueTrendChart rows={data.production.map((r:any)=>({...r,label:`${r.production_date} M${r.machine_id} ${r.shift}`,value:r.oee_reported*100}))} suffix="%" label="OEE"/></section>}{data?.losses?.length>0&&<section className="panel"><h2>Machine losses</h2><ValueTrendChart rows={data.losses.map((r:any)=>({...r,label:`${r.loss_date} M${r.machine_id}`,value:Number(r.duration_min)}))} suffix=" min" label="Loss"/></section>}<section className="panel"><h2>Detailed conditions</h2>{rows.length>0&&<><Records rows={rows}/><div className="button-row">{rows.map((r:any,i:number)=><Link key={i} to={drill(r)}>{r.product||r.action_no||r.kind} · Details</Link>)}</div></>}{data?.repeat_rule&&<p>{data.repeat_rule}</p>}{Object.entries(data||{}).filter(([key,val])=>Array.isArray(val)&&!['exceptions','issues','actions','reminders'].includes(key)).map(([key,val])=><div key={key}><h3>{key}</h3><Records rows={val as any[]}/></div>)}{data?.reminders&&<><h3>In-app reminders</h3><Records rows={data.reminders}/>{data.reminders.filter((r:any)=>!r.acknowledged_at).map((r:any)=><button key={r.id} onClick={async()=>{try{await api(`/insights/reminders/${r.id}/acknowledge`,{method:'POST'});load()}catch(e:any){setError(e.message)}}}>Acknowledge {r.message}</button>)}</>}</section></>
}
