import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { Kpi, PageHeader, Status } from '../components/UI'

const empty:any={code:'',name:'',machine_type:'',plant:'',department:'',cost_center:'',manufacturer:'',model_number:'',serial_number:'',commissioned_on:'',pm_done_date:'',pm_frequency_days:'',default_manpower_required:'',rated_power_kw:'',power_load_factor_percent:75,air_consumption_cfm:'',labor_rate_per_operator_hour:'',electricity_rate_per_kwh:'',compressed_air_rate_per_1000_cuft:'',maintenance_cost_per_hour:0,consumables_cost_per_hour:0,depreciation_cost_per_hour:0,other_overhead_cost_per_hour:0,remarks:'',is_active:true,reason:'Approved machine master revision'}
const optionalNumber=(value:any)=>value===''||value==null?null:Number(value)
const inr=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:2,maximumFractionDigits:2}).format(value||0)

export default function MachineMaster(){
 const [machines,setMachines]=useState<any[]>([]);const [form,setForm]=useState<any>({...empty});const [selected,setSelected]=useState<number|null>(null)
 const [history,setHistory]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('')
 async function load(preferred?:number|null){const rows:any[]=await api('/masters/machines');setMachines(rows);const id=preferred===undefined?selected:preferred;if(id){const found=rows.find(x=>x.id===id);if(found)select(found,false)}}
 useEffect(()=>{load(null)},[])
 async function select(machine:any,fetchHistory=true){setSelected(machine.id);setForm({...empty,...machine,power_load_factor_percent:machine.power_load_factor==null?'':Number(machine.power_load_factor)*100,commissioned_on:machine.commissioned_on||'',pm_done_date:machine.pm_done_date||'',reason:'Approved machine master revision'});if(fetchHistory)setHistory(await api(`/masters/machines/${machine.id}/history`))}
 function newMachine(){setSelected(null);setForm({...empty});setHistory([]);setMsg('')}
 const cost=useMemo(()=>{const manpower=Number(form.default_manpower_required||0);const labor=manpower*Number(form.labor_rate_per_operator_hour||0);const power=Number(form.rated_power_kw||0)*Number(form.power_load_factor_percent||0)/100*Number(form.electricity_rate_per_kwh||0);const air=Number(form.air_consumption_cfm||0)*60/1000*Number(form.compressed_air_rate_per_1000_cuft||0);const fixed=['maintenance_cost_per_hour','consumables_cost_per_hour','depreciation_cost_per_hour','other_overhead_cost_per_hour'].reduce((s,k)=>s+Number(form[k]||0),0);return{labor,power,air,total:labor+power+air+fixed}},[form])
 async function save(){setBusy(true);setMsg('');try{const payload={...form,code:String(form.code).trim(),name:String(form.name).trim(),commissioned_on:form.commissioned_on||null,pm_done_date:form.pm_done_date||null,pm_frequency_days:optionalNumber(form.pm_frequency_days),default_manpower_required:optionalNumber(form.default_manpower_required),rated_power_kw:optionalNumber(form.rated_power_kw),power_load_factor:form.power_load_factor_percent===''?null:Number(form.power_load_factor_percent)/100,air_consumption_cfm:optionalNumber(form.air_consumption_cfm),labor_rate_per_operator_hour:optionalNumber(form.labor_rate_per_operator_hour),electricity_rate_per_kwh:optionalNumber(form.electricity_rate_per_kwh),compressed_air_rate_per_1000_cuft:optionalNumber(form.compressed_air_rate_per_1000_cuft),maintenance_cost_per_hour:optionalNumber(form.maintenance_cost_per_hour),consumables_cost_per_hour:optionalNumber(form.consumables_cost_per_hour),depreciation_cost_per_hour:optionalNumber(form.depreciation_cost_per_hour),other_overhead_cost_per_hour:optionalNumber(form.other_overhead_cost_per_hour)};delete payload.id;delete payload.active;delete payload.next_pm_date;delete payload.cost;delete payload.created_at;delete payload.updated_at;delete payload.power_load_factor_percent;const saved:any=await api(selected?`/masters/machines/${selected}`:'/masters/machines',{method:selected?'PATCH':'POST',body:JSON.stringify(payload)});setMsg(`${saved.code} machine master saved. PM and costing values are now available to planning.`);setSelected(saved.id);await load(saved.id);setHistory(await api(`/masters/machines/${saved.id}/history`))}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 const set=(key:string,value:any)=>setForm({...form,[key]:value})
 return <><PageHeader title="Machine Master" subtitle="Machine identity, PM status, fractional manpower, utilities and transparent hourly cost assumptions." actions={<button className="secondary" onClick={newMachine}>New machine</button>}/>
 {msg&&<div className={msg.includes('saved')?'notice':'warning-box'}>{msg}</div>}
 <div className="kpi-grid"><Kpi label="Machines" value={machines.length}/><Kpi label="Active" value={machines.filter(x=>x.active).length}/><Kpi label="Estimated Hourly Cost" value={inr(cost.total)} sub="Current form assumptions"/><Kpi label="Next PM" value={selected?machines.find(x=>x.id===selected)?.next_pm_date||'Not configured':'—'} tone={selected&&machines.find(x=>x.id===selected)?.pm_status==='Overdue'?'bad':'neutral'} sub={selected?machines.find(x=>x.id===selected)?.pm_status:''}/></div>
 <div className="machine-master-layout"><section className="panel"><h2>Machine list</h2><div className="table-wrap"><table><thead><tr><th>Code / Machine</th><th>Shop</th><th>Manpower</th><th>Power</th><th>Air</th><th>PM</th><th>Cost/hr</th><th></th></tr></thead><tbody>{machines.map(m=><tr key={m.id}><td><b>{m.code}</b><br/><small>{m.name}</small></td><td>{m.plant||'—'} / {m.department||'—'}</td><td>{m.default_manpower_required??'—'}</td><td>{m.rated_power_kw==null?'—':`${m.rated_power_kw} kW`}</td><td>{m.air_consumption_cfm==null?'—':`${m.air_consumption_cfm} CFM`}</td><td>{m.next_pm_date||m.pm_done_date||'—'}<br/><Status value={m.pm_status}/></td><td>{inr(m.cost?.estimated_hourly_cost)}</td><td><button className="small secondary" onClick={()=>select(m)}>Edit</button></td></tr>)}</tbody></table></div></section>
 <section className="panel machine-form"><h2>{selected?'Edit machine':'Create machine'}</h2><h3>Identity and ownership</h3><div className="machine-field-grid"><label>Machine code *<input value={form.code} onChange={e=>set('code',e.target.value)}/></label><label>Machine name *<input value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Machine type<input value={form.machine_type||''} onChange={e=>set('machine_type',e.target.value||null)}/></label><label>Plant / Shop<input value={form.plant||''} onChange={e=>set('plant',e.target.value||null)}/></label><label>Department<input value={form.department||''} onChange={e=>set('department',e.target.value||null)}/></label><label>Cost center<input value={form.cost_center||''} onChange={e=>set('cost_center',e.target.value||null)}/></label><label>Manufacturer<input value={form.manufacturer||''} onChange={e=>set('manufacturer',e.target.value||null)}/></label><label>Model number<input value={form.model_number||''} onChange={e=>set('model_number',e.target.value||null)}/></label><label>Serial / asset number<input value={form.serial_number||''} onChange={e=>set('serial_number',e.target.value||null)}/></label><label>Commissioned on<input type="date" value={form.commissioned_on||''} onChange={e=>set('commissioned_on',e.target.value)}/></label></div>
 <h3>PM and operating requirement</h3><div className="machine-field-grid"><label>Last PM done date<input type="date" value={form.pm_done_date||''} onChange={e=>set('pm_done_date',e.target.value)}/></label><label>PM frequency (days)<input type="number" min="1" value={form.pm_frequency_days??''} onChange={e=>set('pm_frequency_days',e.target.value)}/></label><label>Default manpower<input type="number" min="0.001" step="0.001" value={form.default_manpower_required??''} onChange={e=>set('default_manpower_required',e.target.value)}/><small>Fractions accepted, e.g. 0.5 operator</small></label><label>Rated power (kW)<input type="number" min="0" step="0.001" value={form.rated_power_kw??''} onChange={e=>set('rated_power_kw',e.target.value)}/></label><label>Expected load factor %<input type="number" min="0.01" max="100" step="0.01" value={form.power_load_factor_percent??''} onChange={e=>set('power_load_factor_percent',e.target.value)}/></label><label>Air consumption (CFM)<input type="number" min="0" step="0.001" value={form.air_consumption_cfm??''} onChange={e=>set('air_consumption_cfm',e.target.value)}/></label></div>
 <h3>Cost assumptions</h3><div className="machine-field-grid"><label>Labor ₹/operator-hour<input type="number" min="0" step="0.01" value={form.labor_rate_per_operator_hour??''} onChange={e=>set('labor_rate_per_operator_hour',e.target.value)}/></label><label>Electricity ₹/kWh<input type="number" min="0" step="0.01" value={form.electricity_rate_per_kwh??''} onChange={e=>set('electricity_rate_per_kwh',e.target.value)}/></label><label>Compressed air ₹/1,000 cu ft<input type="number" min="0" step="0.01" value={form.compressed_air_rate_per_1000_cuft??''} onChange={e=>set('compressed_air_rate_per_1000_cuft',e.target.value)}/></label><label>Maintenance ₹/hour<input type="number" min="0" step="0.01" value={form.maintenance_cost_per_hour??''} onChange={e=>set('maintenance_cost_per_hour',e.target.value)}/></label><label>Consumables ₹/hour<input type="number" min="0" step="0.01" value={form.consumables_cost_per_hour??''} onChange={e=>set('consumables_cost_per_hour',e.target.value)}/></label><label>Depreciation ₹/hour<input type="number" min="0" step="0.01" value={form.depreciation_cost_per_hour??''} onChange={e=>set('depreciation_cost_per_hour',e.target.value)}/></label><label>Other overhead ₹/hour<input type="number" min="0" step="0.01" value={form.other_overhead_cost_per_hour??''} onChange={e=>set('other_overhead_cost_per_hour',e.target.value)}/></label></div>
 <div className="cost-breakdown"><span>Labor <b>{inr(cost.labor)}</b></span><span>Power <b>{inr(cost.power)}</b></span><span>Air <b>{inr(cost.air)}</b></span><span>Total <b>{inr(cost.total)}/hr</b></span></div>
 <label>Remarks<textarea value={form.remarks||''} onChange={e=>set('remarks',e.target.value||null)}/></label><label className="inline-check"><input type="checkbox" checked={!!form.is_active} onChange={e=>set('is_active',e.target.checked)}/> Active machine</label><label>Change reason *<input value={form.reason} onChange={e=>set('reason',e.target.value)}/></label><button disabled={busy||!String(form.code).trim()||!String(form.name).trim()||!String(form.reason).trim()} onClick={save}>{busy?'Saving…':selected?'Save machine revision':'Create machine'}</button></section></div>
 {selected&&<section className="panel"><div className="panel-title"><h2>Machine master change history</h2><span>PM and cost assumptions included</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Change</th><th>PM done</th><th>Manpower</th><th>Power</th><th>Air</th><th>Reason</th><th>Changed by</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td>{new Date(x.changed_at).toLocaleString('en-IN')}</td><td><Status value={x.change_type}/></td><td>{x.snapshot.pm_done_date||'—'}</td><td>{x.snapshot.default_manpower_required??'—'}</td><td>{x.snapshot.rated_power_kw??'—'} kW</td><td>{x.snapshot.air_consumption_cfm??'—'} CFM</td><td>{x.reason}</td><td>{x.changed_by||'Legacy data'}</td></tr>)}</tbody></table></div></section>}
 </>
}
