import { useEffect, useState } from 'react'
import { api } from '../api'
import { PageHeader } from '../components/UI'
import { MultiSelect } from '../components/MultiSelect'

function today(){return new Date().toISOString().slice(0,10)}
export default function Masters(){
 const [products,setProducts]=useState<any[]>([]); const [ops,setOps]=useState<any[]>([]); const [machines,setMachines]=useState<any[]>([]); const [vendors,setVendors]=useState<any[]>([]); const [users,setUsers]=useState<any[]>([])
 const [pid,setPid]=useState(''); const [route,setRoute]=useState<any[]>([]); const [draft,setDraft]=useState<any[]>([]); const [effective,setEffective]=useState(today());
 const [valueHistory,setValueHistory]=useState<any[]>([]); const [valueProduct,setValueProduct]=useState<any>(null)
 const [newOp,setNewOp]=useState<any>({operation_id:'',vendor_id:'',standard_yield:1,standard_lead_time_days:0,buffer_qty:0,is_dispatch:false})
 const [map,setMap]=useState<any>({route_operation_id:'',machine_id:'',effective_from:today(),priority:1,ideal_cycle_time_sec:''})
 async function refresh(){const [p,o,m,v,u]=await Promise.all([api('/masters/products'),api('/masters/operations'),api('/masters/machines'),api('/masters/vendors'),api('/masters/users')]);setProducts(p as any[]);setOps(o as any[]);setMachines(m as any[]);setVendors(v as any[]);setUsers(u as any[]);if(!pid&&(p as any[])[0])setPid(String((p as any[])[0].id));if(!newOp.operation_id&&(o as any[])[0])setNewOp((x:any)=>({...x,operation_id:String((o as any[])[0].id)}));if(!map.machine_id&&(m as any[])[0])setMap((x:any)=>({...x,machine_id:String((m as any[])[0].id)}))}
 useEffect(()=>{refresh()},[])
 useEffect(()=>{if(pid)api(`/masters/routes/${pid}`).then((x:any)=>{setRoute(x); const ro=x[0]?.operations||[]; if(ro[0])setMap((m:any)=>({...m,route_operation_id:String(ro[0].route_operation_id)}))})},[pid])
 async function addUser(){const username=prompt('User name');if(!username)return;const full_name=prompt('Full name')||username;const password=prompt('Temporary password (min 8 chars)');if(!password)return;const role=prompt('Role: ADMIN / MANAGEMENT / PRODUCTION / QUALITY / PLANNING / PURCHASE / DISPATCH / VENDOR / VIEW_ONLY','VIEW_ONLY')||'VIEW_ONLY';await api('/masters/users',{method:'POST',body:JSON.stringify({username,full_name,password,role})});refresh()}
 function addDraft(){const op=ops.find(o=>String(o.id)===String(newOp.operation_id)); if(!op)return; setDraft([...draft,{...newOp,operation_id:Number(newOp.operation_id),sequence_no:(draft.length+1)*10,label:op.name,vendor_id:newOp.vendor_id?Number(newOp.vendor_id):null}])}
 async function saveRoute(){if(!pid||!draft.length)return;await api(`/masters/routes/${pid}`,{method:'POST',body:JSON.stringify({effective_from:effective,description:'Route revision created in web app',operations:draft.map(({label,...x})=>x)})});setDraft([]);setRoute(await api(`/masters/routes/${pid}`))}
 async function saveMachineMap(){if(!map.route_operation_id||!map.machine_id)return;const reason=prompt('Reason for machine / cycle master revision','Approved machine setup');if(!reason)return;await api('/masters/machine-maps',{method:'POST',body:JSON.stringify({route_operation_id:Number(map.route_operation_id),machine_id:Number(map.machine_id),effective_from:map.effective_from,effective_to:null,priority:Number(map.priority),reason})});if(map.ideal_cycle_time_sec)await api('/masters/cycle-times',{method:'POST',body:JSON.stringify({route_operation_id:Number(map.route_operation_id),machine_id:Number(map.machine_id),effective_from:map.effective_from,effective_to:null,ideal_cycle_time_sec:Number(map.ideal_cycle_time_sec),standard_cycle_time_sec:null,cavities:1,pieces_per_cycle:1,remark:'Created from Masters',reason})});alert('Machine map / cycle time saved')}
 async function editProductMaster(p:any){const plant=prompt(`Plant for ${p.name}`,p.plant||'')??p.plant;const product_group=prompt('Type / Product Group / Category',p.product_group||'')??p.product_group;const wt=prompt('Finish Weight (Kg/pc)',p.finish_weight_kg==null?'':String(p.finish_weight_kg));if(wt===null)return;await api(`/masters/products/${p.id}`,{method:'PATCH',body:JSON.stringify({plant:plant||null,product_group:product_group||null,finish_weight_kg:wt===''?null:Number(wt)})});await refresh()}
 async function showValueHistory(p:any){setValueProduct(p);setValueHistory(await api(`/masters/products/${p.id}/value-addition-history`))}
 async function reviseValueAddition(p:any){const raw=prompt(`Value addition for ${p.name} (₹/piece)`,p.value_addition_per_piece==null?'':String(p.value_addition_per_piece));if(raw===null)return;const value=Number(raw);if(!Number.isFinite(value)||value<0){alert('Enter a non-negative value');return}const effective_from=prompt('Effective from (YYYY-MM-DD)',today());if(!effective_from)return;const reason=prompt('Reason for this revision');if(!reason)return;await api(`/masters/products/${p.id}/value-addition-revisions`,{method:'POST',body:JSON.stringify({effective_from,value_addition_per_piece:value,reason})});await refresh();await showValueHistory(p)}
 const currentOps=route[0]?.operations||[]
 return <><PageHeader title="Masters & Route Setup" subtitle="Product reporting attributes and effective-dated value addition are maintained with an audit trail." actions={<div className="button-row"><button className="secondary" onClick={addUser}>Add user</button><button onClick={()=>location.href='/machine-master'}>Open Machine Master</button></div>}/>
 <section className="panel"><div className="panel-title"><h2>Product reporting master</h2><span>Imported from PBI_Products · editable here</span></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Customer</th><th>Plant</th><th>Type / Product Group</th><th>Finish Weight</th><th>Value Addition</th><th></th></tr></thead><tbody>{products.map((p:any)=><tr key={p.id}><td><b>{p.name}</b></td><td>{p.customer||'—'}</td><td>{p.plant||'—'}</td><td>{p.product_group||'—'}</td><td>{p.finish_weight_kg==null?'—':`${p.finish_weight_kg} kg/pc`}</td><td>{p.value_addition_per_piece==null?'—':`₹${Number(p.value_addition_per_piece).toLocaleString('en-IN')}/pc`}</td><td><div className="button-row"><button className="small secondary" onClick={()=>editProductMaster(p)}>Edit attributes</button><button className="small" onClick={()=>reviseValueAddition(p)}>Revise value</button><button className="small secondary" onClick={()=>showValueHistory(p)}>History</button></div></td></tr>)}</tbody></table></div></section>
 {valueProduct&&<section className="panel"><div className="panel-title"><h2>Value Addition History — {valueProduct.name}</h2><button className="small secondary" onClick={()=>{setValueProduct(null);setValueHistory([])}}>Close</button></div><p className="muted">Append-only ₹/piece revisions preserve the value that applied on each effective date for future costing.</p><div className="table-wrap"><table><thead><tr><th>Effective From</th><th>₹ / piece</th><th>Reason</th><th>Changed By</th></tr></thead><tbody>{valueHistory.map((x:any)=><tr key={x.id}><td>{x.effective_from}</td><td>₹{Number(x.value_addition_per_piece).toLocaleString('en-IN')}</td><td>{x.reason}</td><td>{x.changed_by||'—'}</td></tr>)}</tbody></table></div></section>}
 <div className="two-col"><section className="panel"><h2>Current product route</h2><label>Product<MultiSelect singleSelect value={pid?[pid]:[]} onChange={v=>setPid(v.at(-1)||'')} placeholder="Select Product" options={products.map(p=>({value:String(p.id),label:p.name}))}/></label>{currentOps.map((x:any)=><div className="master-row" key={x.route_operation_id}><b>{x.sequence_no}. {x.operation}</b><span>{x.type} · Yield {(x.yield*100).toFixed(1)}% · LT {x.lead_time_days}d</span></div>)}</section>
 <section className="panel"><h2>Create new route revision</h2><label>Effective from<input type="date" value={effective} onChange={e=>setEffective(e.target.value)}/></label><div className="form-row"><label>Operation<MultiSelect singleSelect value={newOp.operation_id?[String(newOp.operation_id)]:[]} onChange={v=>setNewOp({...newOp,operation_id:v.at(-1)||''})} placeholder="Select Operation" options={ops.map(o=>({value:String(o.id),label:`${o.name} — ${o.type}`}))}/></label><label>Vendor<MultiSelect singleSelect value={newOp.vendor_id?[String(newOp.vendor_id)]:[]} onChange={v=>setNewOp({...newOp,vendor_id:v.at(-1)||''})} placeholder="None" options={vendors.map(v=>({value:String(v.id),label:v.name}))}/></label></div><div className="form-row"><label>Yield<input type="number" step="0.001" min="0.01" max="1" value={newOp.standard_yield} onChange={e=>setNewOp({...newOp,standard_yield:Number(e.target.value)})}/></label><label>Lead time days<input type="number" min="0" value={newOp.standard_lead_time_days} onChange={e=>setNewOp({...newOp,standard_lead_time_days:Number(e.target.value)})}/></label></div><label className="inline-check"><input type="checkbox" checked={newOp.is_dispatch} onChange={e=>setNewOp({...newOp,is_dispatch:e.target.checked})}/> Dispatch/final operation</label><div className="button-row"><button className="secondary" onClick={addDraft}>Add operation</button><button disabled={!draft.length} onClick={saveRoute}>Save route revision</button></div>{draft.map((x:any,i:number)=><div className="master-row" key={i}><b>{i+1}. {x.label}</b><span>{(Number(x.standard_yield)*100).toFixed(1)}% · {x.standard_lead_time_days}d</span></div>)}</section></div>
 <div className="two-col"><section className="panel"><h2>Machine / cycle time mapping</h2><label>Route operation<MultiSelect singleSelect value={map.route_operation_id?[String(map.route_operation_id)]:[]} onChange={v=>setMap({...map,route_operation_id:v.at(-1)||''})} placeholder="Select Operation" options={currentOps.map((o:any)=>({value:String(o.route_operation_id),label:o.operation}))}/></label><label>Machine<MultiSelect singleSelect value={map.machine_id?[String(map.machine_id)]:[]} onChange={v=>setMap({...map,machine_id:v.at(-1)||''})} placeholder="Select Machine" options={machines.map(m=>({value:String(m.id),label:`${m.code} — ${m.name}`}))}/></label><div className="form-row"><label>Effective from<input type="date" value={map.effective_from} onChange={e=>setMap({...map,effective_from:e.target.value})}/></label><label>Priority<input type="number" min="1" value={map.priority} onChange={e=>setMap({...map,priority:Number(e.target.value)})}/></label></div><label>Ideal cycle time (sec)<input type="number" step="0.01" value={map.ideal_cycle_time_sec} onChange={e=>setMap({...map,ideal_cycle_time_sec:e.target.value})}/></label><button onClick={saveMachineMap}>Save machine mapping</button></section>
 <section className="panel"><h2>Master counts</h2><div className="master-row"><b>Products</b><span>{products.length}</span></div><div className="master-row"><b>Operations</b><span>{ops.length}</span></div><div className="master-row"><b>Machines</b><span>{machines.length}</span></div><div className="master-row"><b>Vendors</b><span>{vendors.length}</span></div><div className="master-row"><b>Users</b><span>{users.length}</span></div><p className="muted">Imported Excel routes are drafts. Confirm yield, lead time, vendor and machine masters before relying on process-level planning.</p></section></div></>
}
