import { Link } from 'react-router-dom'
import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { Kpi, PageHeader, num, pct } from '../components/UI'

function today(){return new Date().toISOString().slice(0,10)}
const emptyEntry={shift_duration_min:480,planned_break_min:45,downtime_min:0,total_count:0,good_count:0,reject_count:0,ideal_cycle_time_sec:0,remarks:''}
const emptyLoss={loss_category_id:'',duration_min:0,qty_loss:0,remark:''}

export default function OEE(){
 const [allMachines,setAllMachines]=useState<any[]>([]),[machines,setMachines]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[lossCategories,setLossCategories]=useState<any[]>([]),[routes,setRoutes]=useState<any[]>([])
 const [m,setM]=useState(''),[p,setP]=useState(''),[op,setOp]=useState(''),[d,setD]=useState(today()),[shift,setShift]=useState('A')
 const [sum,setSum]=useState<any>(null),[context,setContext]=useState<any>(null),[entryId,setEntryId]=useState<number|null>(null)
 const [entry,setEntry]=useState<any>(emptyEntry),[loss,setLoss]=useState<any>(emptyLoss),[reason,setReason]=useState(''),[msg,setMsg]=useState(''),[error,setError]=useState('')
 const [mgmt,setMgmt]=useState<any>(null),[fromDate,setFromDate]=useState(today().slice(0,8)+'01')
 const selectedProduct=products.find(x=>String(x.id)===p),selectedMachine=machines.find(x=>String(x.id)===m),selectedRoute=routes.find(x=>String(x.route_operation_id)===op)

 useEffect(()=>{Promise.all([api('/masters/machines'),api('/masters/products'),api('/masters/loss-categories')]).then(([ms,ps,ls]:any[])=>{setAllMachines(ms);setMachines(ms.filter((x:any)=>x.active));setProducts(ps);setLossCategories(ls);if(ps[0])setP(String(ps[0].id));if(ls[0])setLoss({...emptyLoss,loss_category_id:String(ls[0].id)})}).catch((e:any)=>setError(e.message))},[])
 useEffect(()=>{if(!p)return;api(`/masters/routes/${p}?on_date=${d}`).then((versions:any)=>{const active=versions.find((v:any)=>v.effective_from<=d&&(!v.effective_to||v.effective_to>=d))||versions[0];const ops=active?.operations||[];setRoutes(ops);setOp(ops[0]?String(ops[0].route_operation_id):'')}).catch((e:any)=>setError(e.message))},[p,d])
 useEffect(()=>{if(!op)return;api(`/oee/available-machines?route_operation_id=${op}&production_date=${d}`).then((r:any)=>{const available=r.machines||allMachines.filter(x=>x.active);setMachines(available);setM(old=>available.some((x:any)=>String(x.id)===old)?old:(available[0]?String(available[0].id):''));if(r.warning)setMsg(r.warning)}).catch((e:any)=>setError(e.message))},[op,d,allMachines])

 async function loadContext(){
  if(!p||!op||!m)return
  try{
   const r:any=await api(`/oee/entry-context?product_id=${p}&route_operation_id=${op}&machine_id=${m}&production_date=${d}&shift=${shift}`)
   setContext(r);setError('')
   if(r.existing_entry){const x=r.existing_entry;setEntryId(x.id);setEntry({shift_duration_min:x.shift_duration_min,planned_break_min:x.planned_break_min,downtime_min:x.downtime_min,total_count:x.total_count,good_count:x.good_count,reject_count:x.reject_count,ideal_cycle_time_sec:x.ideal_cycle_time_sec,remarks:x.remarks||''})}
   else{setEntryId(null);setEntry({...emptyEntry,ideal_cycle_time_sec:r.ideal_cycle_time_sec||0})}
  }catch(e:any){setContext(null);setEntryId(null);setError(e.message)}
 }
 async function refresh(){if(!m)return;try{const q=new URLSearchParams({machine_id:m,summary_date:d,shift});if(p)q.set('product_id',p);if(op)q.set('route_operation_id',op);setSum(await api(`/oee/machine-summary?${q}`))}catch(e:any){setError(e.message)}}
 useEffect(()=>{loadContext();refresh()},[m,p,op,d,shift])
 async function loadManagement(){try{const q=new URLSearchParams({from_date:fromDate,to_date:d});if(p)q.set('product_id',p);setMgmt(await api(`/oee/management-summary?${q}`))}catch(e:any){setError(e.message)}}
 useEffect(()=>{loadManagement()},[fromDate,d,p])

 const clientWarnings=useMemo(()=>{
  const rows:string[]=[];if(Number(entry.good_count)+Number(entry.reject_count)<Number(entry.total_count))rows.push('Some output is not classified as good or reject.');if(Number(entry.downtime_min)>0&&!sum?.losses?.length)rows.push('Downtime is entered but no loss event is classified.');return rows
 },[entry,sum])
 async function save(){
  if(!p||!op||!m){setError('Select product, operation and machine.');return}
  if(entryId&&!reason.trim()){setError('Enter a correction reason to update the existing shift entry.');return}
  try{const body={...entry,production_date:d,shift,product_id:Number(p),route_operation_id:Number(op),machine_id:Number(m)};const path=entryId?`/oee/machine-entry/${entryId}`:'/oee/machine-entry';const r:any=await api(path,{method:entryId?'PUT':'POST',headers:entryId?{'X-Change-Reason':reason}:{},body:JSON.stringify(body)});setMsg(`${entryId?'Shift entry corrected':'Shift entry saved'}${r.warnings?.length?` — ${r.warnings.join('; ')}`:''}`);setReason('');setError('');await loadContext();await refresh()}catch(e:any){setError(e.message)}
 }
 async function addLoss(){
  if(!loss.loss_category_id||Number(loss.duration_min)<=0){setError('Select a loss category and enter minutes greater than zero.');return}
  try{await api('/oee/loss-events',{method:'POST',body:JSON.stringify({loss_date:d,shift,product_id:Number(p),route_operation_id:Number(op),machine_id:Number(m),loss_category_id:Number(loss.loss_category_id),duration_min:Number(loss.duration_min),qty_loss:Number(loss.qty_loss),remark:loss.remark})});setLoss({...emptyLoss,loss_category_id:loss.loss_category_id});setMsg('Loss event saved and included in reconciliation.');setError('');await refresh()}catch(e:any){setError(e.message)}
 }
 async function raiseOeeAction(){try{const r:any=await api('/oee/raise-action',{method:'POST',body:JSON.stringify({production_date:d,shift,product_id:Number(p),route_operation_id:Number(op),machine_id:Number(m),target_oee:.85})});setMsg(`${r.action_no} ${r.status==='already_linked'?'is already open':'created with a standard Why-Why plan'}`);await refresh()}catch(e:any){setError(e.message)}}
 async function raiseLossAction(id:number){try{const r:any=await api(`/oee/loss-events/${id}/raise-action`,{method:'POST',body:JSON.stringify({priority:'HIGH'})});setMsg(`${r.action_no} ${r.status==='already_linked'?'is already linked':'created with a standard Why-Why plan'}`);await refresh()}catch(e:any){setError(e.message)}}
 const s=sum?.summary
 return <>
  <PageHeader title="Machine / OEE" subtitle="Capture one controlled record per machine, product, operation and shift; reconcile losses and raise standard action plans from the same page." actions={<div className="form-row compact"><input aria-label="Production date" type="date" value={d} onChange={e=>setD(e.target.value)}/><select aria-label="Shift" value={shift} onChange={e=>setShift(e.target.value)}><option>A</option><option>B</option><option>C</option></select></div>}/>
  <section className="panel oee-scope"><div className="filters"><label>Product<select value={p} onChange={e=>setP(e.target.value)}><option value="">Select product</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Operation<select value={op} onChange={e=>setOp(e.target.value)}><option value="">Select operation</option>{routes.map(x=><option key={x.route_operation_id} value={x.route_operation_id}>{x.sequence_no}. {x.operation}</option>)}</select></label><label>Mapped machine<select value={m} onChange={e=>setM(e.target.value)}><option value="">Select machine</option>{machines.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label></div><p className="muted">{selectedProduct?.name||'Product'} → {selectedRoute?.operation||'Operation'} → {selectedMachine?.code||'Machine'} • Effective ideal cycle: <b>{context?.ideal_cycle_time_sec??'missing'} sec/part</b></p>{context?.warnings?.map((x:string)=><div className="warning-box" key={x}>{x}</div>)}</section>
  {error&&<div className="error" role="alert">{error}</div>}{msg&&<div className="notice" role="status">{msg}</div>}
  {s&&<><div className="kpi-grid"><Kpi label="OEE" value={pct(s.oee_reported)} tone={s.oee_reported<.6?'bad':s.oee_reported<.85?'warn':'good'}/><Kpi label="Availability" value={pct(s.availability)}/><Kpi label="Performance" value={pct(s.performance_raw)} tone={s.performance_master_warning?'warn':'neutral'}/><Kpi label="Quality" value={pct(s.quality)}/><Kpi label="Availability loss classified" value={`${num(s.captured_loss_min)} min`}/><Kpi label="Downtime unclassified" value={`${num(s.unclassified_loss_min)} min`} tone={s.unclassified_loss_min>0?'bad':'good'}/></div>{s.overclassified_loss_min>0&&<div className="error">Availability loss events exceed entered downtime by {num(s.overclassified_loss_min)} minutes. Correct the entry or loss records.</div>}</>}
  <div className="two-col wide-left"><section className="panel"><div className="panel-title"><div><h2>Machine shift production</h2><p>{entryId?`Loaded entry #${entryId}. Saving will create an audited correction.`:'No existing row for this scope; saving creates the shift record.'}</p></div></div><div className="oee-entry-grid"><label>Shift duration (min)<input type="number" min="1" value={entry.shift_duration_min} onChange={e=>setEntry({...entry,shift_duration_min:Number(e.target.value)})}/></label><label>Planned break (min)<input type="number" min="0" value={entry.planned_break_min} onChange={e=>setEntry({...entry,planned_break_min:Number(e.target.value)})}/></label><label>Downtime (min)<input type="number" min="0" value={entry.downtime_min} onChange={e=>setEntry({...entry,downtime_min:Number(e.target.value)})}/></label><label>Total produced<input type="number" min="0" value={entry.total_count} onChange={e=>setEntry({...entry,total_count:Number(e.target.value)})}/></label><label>Good quantity<input type="number" min="0" value={entry.good_count} onChange={e=>setEntry({...entry,good_count:Number(e.target.value)})}/></label><label>Reject quantity<input type="number" min="0" value={entry.reject_count} onChange={e=>setEntry({...entry,reject_count:Number(e.target.value)})}/></label><label>Ideal cycle (master)<input type="number" value={entry.ideal_cycle_time_sec} readOnly/></label><label className="span-2">Shift remarks<textarea value={entry.remarks} onChange={e=>setEntry({...entry,remarks:e.target.value})}/></label>{entryId&&<label className="span-2">Correction reason<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required when changing the saved entry"/></label>}</div>{clientWarnings.map(x=><div className="warning-box" key={x}>{x}</div>)}<div className="button-row"><button onClick={save}>{entryId?'Save audited correction':'Save shift entry'}</button><button className="secondary" onClick={raiseOeeAction} disabled={!s}>Raise OEE action</button></div></section>
   <section className="panel"><h2>Add classified loss</h2><label>Loss category<select value={loss.loss_category_id} onChange={e=>setLoss({...loss,loss_category_id:e.target.value})}><option value="">Select loss</option>{lossCategories.map(x=><option key={x.id} value={x.id}>{x.name} — {x.component}</option>)}</select></label><label>Duration (min)<input type="number" min="0.01" step="0.01" value={loss.duration_min} onChange={e=>setLoss({...loss,duration_min:Number(e.target.value)})}/></label><label>Quantity loss<input type="number" min="0" step="0.001" value={loss.qty_loss} onChange={e=>setLoss({...loss,qty_loss:Number(e.target.value)})}/></label><label>Loss remark<textarea value={loss.remark} onChange={e=>setLoss({...loss,remark:e.target.value})} placeholder="Breakdown symptom, tool, reason or observation"/></label><button onClick={addLoss}>Add loss event</button><p className="muted">Only Availability-category minutes reconcile against downtime. Performance and Quality losses remain visible without incorrectly consuming downtime.</p></section></div>
  <section className="panel"><div className="panel-title"><div><h2>Loss reconciliation and actions</h2><p>Classify every downtime minute; raise an action for major or recurring losses.</p></div><Link to="/actions">Open action register</Link></div><div className="table-wrap"><table><thead><tr><th>Loss</th><th>OEE component</th><th>Minutes</th><th>Qty loss</th><th>Remark</th><th>Action</th></tr></thead><tbody>{(sum?.losses||[]).map((x:any)=><tr key={x.id}><td><b>{x.category}</b></td><td>{x.component}</td><td>{num(x.duration_min)}</td><td>{num(x.qty_loss)}</td><td>{x.remark||'—'}</td><td>{x.action_no?<Link to="/actions">{x.action_no} · {x.action_status}</Link>:<button className="small" onClick={()=>raiseLossAction(x.id)}>Raise action</button>}</td></tr>)}{!sum?.losses?.length&&<tr><td colSpan={6} className="muted">No loss events for this selected scope.</td></tr>}</tbody></table></div></section>
  <section className="panel"><div className="panel-title"><div><h2>OEE Management — Trend & Loss Pareto</h2><p>Period performance across machines using the same controlled shift records.</p></div><div className="form-row compact"><input aria-label="OEE from date" type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/><button className="secondary" onClick={loadManagement}>Refresh</button></div></div>
  {mgmt&&<><div className="kpi-grid"><Kpi label="Period OEE" value={pct(mgmt.overall?.oee_reported)}/><Kpi label="Availability" value={pct(mgmt.overall?.availability)}/><Kpi label="Performance" value={pct(mgmt.overall?.performance_raw)}/><Kpi label="Quality" value={pct(mgmt.overall?.quality)}/><Kpi label="Shift Records" value={mgmt.entry_count||0}/><Kpi label="Loss Events" value={mgmt.loss_event_count||0}/></div>
  <div className="two-col"><div className="table-wrap"><table><thead><tr><th>Machine</th><th>Records</th><th>A</th><th>P</th><th>Q</th><th>OEE</th></tr></thead><tbody>{(mgmt.machines||[]).map((x:any)=><tr key={x.machine_id}><td><b>{x.machine}</b></td><td>{x.entry_count}</td><td>{pct(x.availability)}</td><td>{pct(x.performance_raw)}</td><td>{pct(x.quality)}</td><td><b>{pct(x.oee_reported)}</b></td></tr>)}{!mgmt.machines?.length&&<tr><td colSpan={6} className="muted">No OEE records in this period.</td></tr>}</tbody></table></div>
  <div className="table-wrap"><table><thead><tr><th>Loss</th><th>Component</th><th>Events</th><th>Minutes</th><th>Qty loss</th></tr></thead><tbody>{(mgmt.loss_pareto||[]).slice(0,10).map((x:any)=><tr key={x.category}><td><b>{x.category}</b></td><td>{x.component||'—'}</td><td>{x.events}</td><td>{num(x.minutes)}</td><td>{num(x.qty_loss)}</td></tr>)}{!mgmt.loss_pareto?.length&&<tr><td colSpan={5} className="muted">No classified losses in this period.</td></tr>}</tbody></table></div></div>
  <div className="table-wrap"><table><thead><tr><th>Date</th><th>A</th><th>P</th><th>Q</th><th>OEE</th></tr></thead><tbody>{(mgmt.trend||[]).map((x:any)=><tr key={x.date}><td>{x.date}</td><td>{pct(x.availability)}</td><td>{pct(x.performance_raw)}</td><td>{pct(x.quality)}</td><td><b>{pct(x.oee_reported)}</b></td></tr>)}</tbody></table></div></>}</section>
  <section className="panel"><div className="panel-title"><div><h2>Saved OEE records</h2><p>One row per selected machine, product, operation and shift.</p></div><Link to={`/insights?kind=oee&from_date=${d}&to_date=${d}&machine_id=${m}`}>Open drill-down</Link></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Total</th><th>Good</th><th>Reject</th><th>Downtime</th><th>Cycle</th><th>A</th><th>P</th><th>Q</th><th>OEE</th></tr></thead><tbody>{(sum?.entries||[]).map((x:any)=><tr key={x.id}><td>#{x.id}</td><td>{num(x.total_count)}</td><td>{num(x.good_count)}</td><td>{num(x.reject_count)}</td><td>{num(x.downtime_min)} min</td><td>{num(x.ideal_cycle_time_sec)} sec</td><td>{pct(x.availability)}</td><td className={x.performance_master_warning?'neg':''}>{pct(x.performance_raw)}</td><td>{pct(x.quality)}</td><td><b>{pct(x.oee_reported)}</b></td></tr>)}{!sum?.entries?.length&&<tr><td colSpan={10} className="muted">No shift entry saved yet.</td></tr>}</tbody></table></div></section>
 </>
}
