import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { MultiSelect } from '../components/MultiSelect'
import { PageHeader } from '../components/UI'

const today=()=>new Date().toISOString().slice(0,10)

export default function ProductMaster(){
 const [products,setProducts]=useState<any[]>([]); const [customers,setCustomers]=useState<any[]>([])
 const [plant,setPlant]=useState(''); const [group,setGroup]=useState(''); const [customer,setCustomer]=useState(''); const [search,setSearch]=useState('')
 const [editing,setEditing]=useState<any>(null); const [historyProduct,setHistoryProduct]=useState<any>(null); const [history,setHistory]=useState<any[]>([])
 const [err,setErr]=useState(''); const [message,setMessage]=useState('')
 async function refresh(){try{setErr('');const [p,c]:any=await Promise.all([api('/masters/products'),api('/masters/customers')]);setProducts(p);setCustomers(c)}catch(e:any){setErr(e.message)}}
 useEffect(()=>{refresh()},[])
 const plants=useMemo(()=>Array.from(new Set(products.map(p=>p.plant).filter(Boolean))).sort(),[products])
 const groups=useMemo(()=>Array.from(new Set(products.map(p=>p.product_group).filter(Boolean))).sort(),[products])
 const visible=useMemo(()=>products.filter(p=>(!plant||p.plant===plant)&&(!group||p.product_group===group)&&(!customer||String(p.customer_id)===customer)&&(!search.trim()||`${p.code} ${p.name} ${p.customer||''}`.toLowerCase().includes(search.trim().toLowerCase()))),[products,plant,group,customer,search])
 async function saveAttributes(e:React.FormEvent){e.preventDefault();if(!editing)return;try{await api(`/masters/products/${editing.id}`,{method:'PATCH',body:JSON.stringify({plant:editing.plant||null,product_group:editing.product_group||null,finish_weight_kg:editing.finish_weight_kg===''?null:Number(editing.finish_weight_kg)})});setEditing(null);await refresh();setMessage('Product attributes updated.')}catch(e:any){setErr(e.message)}}
 async function reviseValue(p:any){const raw=prompt(`Value addition for ${p.name} (₹/piece)`,p.value_addition_per_piece==null?'':String(p.value_addition_per_piece));if(raw===null)return;const value=Number(raw);if(!Number.isFinite(value)||value<0){alert('Enter a non-negative value');return}const effective_from=prompt('Effective from (YYYY-MM-DD)',today());if(!effective_from)return;const reason=prompt('Reason for value-addition revision');if(!reason?.trim())return;try{await api(`/masters/products/${p.id}/value-addition-revisions`,{method:'POST',body:JSON.stringify({effective_from,value_addition_per_piece:value,reason:reason.trim()})});await refresh();if(historyProduct?.id===p.id)await showHistory(p);setMessage('Part-wise value addition revised with history.')}catch(e:any){setErr(e.message)}}
 async function showHistory(p:any){try{setHistoryProduct(p);setHistory(await api(`/masters/products/${p.id}/value-addition-history`))}catch(e:any){setErr(e.message)}}
 return <><PageHeader title="Product Update" subtitle="Maintain product reporting attributes and part-wise value addition with effective-date history."/>
 {err&&<div className="error">{err}</div>}{message&&<div className="notice">{message}</div>}
 <section className="panel"><div className="panel-title"><h2>Filters</h2><span>{visible.length} of {products.length} products</span></div><div className="form-row">
 <label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Part code, name or customer"/></label>
 <label>Plant<MultiSelect className="manual-search-select" value={plant?[plant]:[]} onChange={v=>setPlant(v.at(-1)||'')} placeholder="All Plants" options={plants.map(x=>({value:String(x),label:String(x)}))}/></label>
 <label>Product Group<MultiSelect className="manual-search-select" value={group?[group]:[]} onChange={v=>setGroup(v.at(-1)||'')} placeholder="All Groups" options={groups.map(x=>({value:String(x),label:String(x)}))}/></label>
 <label>Customer<MultiSelect className="manual-search-select" value={customer?[customer]:[]} onChange={v=>setCustomer(v.at(-1)||'')} placeholder="All Customers" options={customers.map(c=>({value:String(c.id),label:c.name}))}/></label>
 </div></section>
 <section className="panel"><div className="panel-title"><h2>Product Master</h2><span>₹ value addition is maintained per piece</span></div><div className="table-wrap"><table><thead><tr><th>Part Code</th><th>Product</th><th>Customer</th><th>Plant</th><th>Product Group</th><th>Finish Weight</th><th>Value Addition ₹/pc</th><th>Update</th></tr></thead><tbody>{visible.map((p:any)=><tr key={p.id}><td><b>{p.code}</b></td><td>{p.name}</td><td>{p.customer||'—'}</td><td>{p.plant||'—'}</td><td>{p.product_group||'—'}</td><td>{p.finish_weight_kg==null?'—':`${p.finish_weight_kg} kg`}</td><td><b>{p.value_addition_per_piece==null?'—':`₹${Number(p.value_addition_per_piece).toLocaleString('en-IN',{maximumFractionDigits:3})}`}</b></td><td><div className="button-row"><button className="small secondary" onClick={()=>setEditing({...p,finish_weight_kg:p.finish_weight_kg??''})}>Edit Product</button><button className="small" onClick={()=>reviseValue(p)}>Revise Value</button><button className="small secondary" onClick={()=>showHistory(p)}>Value History</button></div></td></tr>)}</tbody></table></div></section>
 {editing&&<section className="panel"><div className="panel-title"><h2>Update Product — {editing.name}</h2><button className="small secondary" onClick={()=>setEditing(null)}>Cancel</button></div><form onSubmit={saveAttributes}><div className="form-row"><label>Plant<input value={editing.plant||''} onChange={e=>setEditing({...editing,plant:e.target.value})}/></label><label>Product Group<input value={editing.product_group||''} onChange={e=>setEditing({...editing,product_group:e.target.value})}/></label><label>Finish Weight (kg/pc)<input type="number" min="0" step="0.0001" value={editing.finish_weight_kg} onChange={e=>setEditing({...editing,finish_weight_kg:e.target.value})}/></label></div><button>Save Product</button></form></section>}
 {historyProduct&&<section className="panel"><div className="panel-title"><h2>Value Addition History — {historyProduct.name}</h2><button className="small secondary" onClick={()=>{setHistoryProduct(null);setHistory([])}}>Close</button></div><div className="table-wrap"><table><thead><tr><th>Effective From</th><th>Value Addition ₹/pc</th><th>Reason</th><th>Changed By</th><th>Changed At</th></tr></thead><tbody>{history.map((x:any)=><tr key={x.id}><td>{x.effective_from}</td><td><b>₹{Number(x.value_addition_per_piece).toLocaleString('en-IN',{maximumFractionDigits:3})}</b></td><td>{x.reason}</td><td>{x.changed_by||'—'}</td><td>{String(x.created_at||'').replace('T',' ').slice(0,16)||'—'}</td></tr>)}</tbody></table></div>{!history.length&&<div className="empty">No value-addition revisions recorded yet.</div>}</section>}
 </>}
