import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { api, getToken } from '../api'
import { PageHeader } from '../components/UI'

const numberFields=['actual','good_count','shift_duration_min','planned_break_min','downtime_min','ideal_cycle_time_sec']
const labels:any={actual:'Fresh total quantity',good_count:'Good quantity',shift_duration_min:'Shift minutes',planned_break_min:'Planned break minutes',downtime_min:'Downtime minutes',ideal_cycle_time_sec:'Ideal cycle seconds / piece'}
export default function ShopCapture(){
 const [inbox,setInbox]=useState<any[]>([]),[capture,setCapture]=useState<any>(null),[draft,setDraft]=useState<any>(null)
 const [machines,setMachines]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[routes,setRoutes]=useState<any[]>([])
 const [selected,setSelected]=useState(-1),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reason,setReason]=useState(''),[preview,setPreview]=useState<any>(null),[dirty,setDirty]=useState(false),[image,setImage]=useState('')
 const locked=capture?.status==='imported'
 async function refresh(){setInbox(await api('/shop-capture'))}
 useEffect(()=>{Promise.all([refresh(),api('/masters/machines').then(setMachines),api('/masters/products').then(setProducts)]).catch(e=>setMessage(e.message))},[])
 useEffect(()=>{if(!capture)return;let url='',alive=true;fetch(`${import.meta.env.VITE_API_URL||'/api'}/shop-capture/${capture.id}/image`,{headers:{Authorization:`Bearer ${getToken()}`}}).then(r=>{if(!r.ok)throw new Error('Source image unavailable');return r.blob()}).then(b=>{url=URL.createObjectURL(b);if(alive)setImage(url);else URL.revokeObjectURL(url)}).catch(e=>{if(alive)setMessage(e.message)});return()=>{alive=false;URL.revokeObjectURL(url);setImage('')}},[capture?.id])
 const row=draft?.rows[selected]
 useEffect(()=>{setRoutes([]);if(row?.product_id){let active=true;api(`/masters/routes/${row.product_id}`).then((r:any[])=>{if(active)setRoutes(r.flatMap(v=>v.operations.map((o:any)=>({...o,version:v.revision_no}))))}).catch(e=>setMessage(e.message));return()=>{active=false}}},[row?.product_id])
 async function run(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 function load(x:any){setCapture(x);setDraft(x.draft);setSelected(-1);setPreview(null);setDirty(false);setReason('')}
 function edit(values:any){setDraft({...draft,...values});setDirty(true);setPreview(null)}
 function editRow(values:any){edit({rows:draft.rows.map((r:any,i:number)=>i===selected?{...r,...values}:r)})}
 async function open(id:number){if(dirty&&!confirm('Discard unsaved edits and open another report?'))return;await run(async()=>load(await api(`/shop-capture/${id}`)))}
 async function upload(files:FileList|null){if(!files?.length)return;if(dirty&&!confirm('Discard unsaved edits and upload?'))return;await run(async()=>{let last:any;for(const f of Array.from(files)){const data=new FormData();data.append('file',f);last=await api('/shop-capture/upload',{method:'POST',body:data});await refresh()}load(last);setMessage(last.duplicate?'This image already exists. Its saved draft has been reopened.':'OCR completed. Check the date, shop, figures and every source line before import.')})}
 async function save(){const x=await api(`/shop-capture/${capture.id}`,{method:'PUT',body:JSON.stringify({revision:capture.revision,reason,draft})});setCapture(x);setDraft(x.draft);setDirty(false);setPreview(null);return x}
 return <><PageHeader title="Shop Production Capture" subtitle="Upload report images → review OCR → map machines → validate → import"/>
 {message&&<div className="notice" role="status">{message}</div>}
 <section className="panel"><label>Upload PNG / JPG / WebP reports (up to 15 MB and 16 megapixels each)<input type="file" accept="image/png,image/jpeg,image/webp" multiple disabled={busy} onChange={e=>{upload(e.target.files);e.target.value=''}}/></label><p>OCR runs on your application server. Each image becomes a saved draft. English printed text is supported; always check OCR figures.</p><label>Saved reports<select disabled={busy} value={capture?.id||''} onChange={e=>e.target.value&&open(Number(e.target.value))}><option value="">Choose a report</option>{inbox.map(x=><option key={x.id} value={x.id}>#{x.id} · {x.source_name} · {x.status==='imported'?'Selected machine rows imported':x.status}</option>)}</select></label>{busy&&<p role="status">Working… OCR may take up to 45 seconds per image.</p>}</section>
 {draft&&<><div className="two-col"><section className="panel"><h2>1. Source and transcription</h2>{image&&<img src={image} alt="Original uploaded production report" style={{maxWidth:'100%',maxHeight:500,objectFit:'contain'}}/>}<details><summary>Original OCR text</summary><pre style={{whiteSpace:'pre-wrap'}}>{capture.original_text||'No text detected. Enter a transcription below.'}</pre></details><label>Corrected transcription<textarea rows={12} value={draft.text} disabled={busy||locked||capture.receipt.length>0} onChange={e=>edit({text:e.target.value,rows:[]})}/></label><label>Meaning of numeric pairs<select value={draft.pair_order} disabled={busy||locked||capture.receipt.length>0} onChange={e=>edit({pair_order:e.target.value,rows:[]})}><option value="unknown">Needs confirmation</option><option value="target-actual">Target : Actual</option><option value="actual-target">Actual / Target</option></select></label><button disabled={busy||locked||capture.receipt.length>0} onClick={()=>run(async()=>{if(draft.rows.length&&!confirm('Re-extracting resets row mappings and edits. Continue?'))return;const x=await api('/shop-capture/parse',{method:'POST',body:JSON.stringify({text:draft.text,pair_order:draft.pair_order})});edit({...x,plant:draft.plant,shop:draft.shop,production_date:draft.production_date||x.production_date,shift:draft.shift||x.shift});setSelected(-1)})}>Extract / re-extract figures</button><p>Changing transcription or pair order clears extracted rows. Save your review to retain an audit version.</p></section>
 <section className="panel"><h2>2. Report identity</h2><label>Plant<select disabled={busy||locked||capture.receipt.length>0} value={draft.plant} onChange={e=>edit({plant:e.target.value})}><option value="">Confirm plant</option>{Array.from(new Set(products.map(p=>p.plant).filter(Boolean))).map(p=><option key={p}>{p}</option>)}</select></label><label>Shop<input disabled={busy||locked||capture.receipt.length>0} list="capture-shops" value={draft.shop} onChange={e=>edit({shop:e.target.value})}/><datalist id="capture-shops">{Array.from(new Set(machines.map(m=>m.department).filter(Boolean))).map(s=><option key={s} value={s}/>)}</datalist></label><label>Date<input type="date" disabled={busy||locked||capture.receipt.length>0} value={draft.production_date} onChange={e=>edit({production_date:e.target.value})}/></label><label>Confirm shift<select disabled={busy||locked||capture.receipt.length>0} value={['A','B','C'].includes(draft.shift)?draft.shift:''} onChange={e=>edit({shift:e.target.value})}><option value="">Select A, B or C (OCR: {draft.shift||'missing'})</option><option>A</option><option>B</option><option>C</option></select></label><p>Stated duration: {draft.stated_hours?`${draft.stated_hours} hours`:'not detected'}. Confirm timings for each machine.</p><div className="notice">Import supports complete fresh machine-production rows. Stock, dispatch, quality totals, rework and mixed-product totals remain source observations. They do not automatically update MIS or stage actuals.</div><label>Review / correction reason<input disabled={busy||locked} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||locked||reason.trim().length<3} onClick={()=>run(async()=>{await save();setMessage('Review saved with correction history.');await refresh()})}>Save review</button>{dirty&&<p>Unsaved changes</p>}<details><summary>Review history ({capture.history.length})</summary>{capture.history.map((h:any,i:number)=><p key={i}>{h.at} · User #{h.actor_id} · {h.reason||h.event}</p>)}</details></section></div>
 <section className="panel"><h2>3. Figures and mapping</h2><p>{draft.rows.length} source rows · {draft.rows.filter((r:any)=>r.disposition==='machine').length} selected for machine import · {draft.rows.filter((r:any)=>r.disposition==='pending').length} pending</p><div style={{overflowX:'auto',maxHeight:460}}><table><thead><tr><th>Line / machine</th><th>Product hint</th><th>Target</th><th>Actual</th><th>Disposition</th><th>Checks</th><th/></tr></thead><tbody>{draft.rows.map((r:any,i:number)=><tr key={i}><td>{r.source_line}. {r.label}</td><td>{r.product_hint}</td><td>{r.target??'—'}</td><td>{r.actual??'—'}</td><td>{r.disposition}</td><td>{r.warnings.join('; ')}</td><td><button disabled={busy} onClick={()=>setSelected(i)}>Review</button></td></tr>)}</tbody></table></div>
 {row&&<fieldset disabled={busy||locked||row.disposition==='imported'} style={{marginTop:20}}><legend>Review source line {row.source_line}</legend><p>{row.source_text}</p><label>Destination<select value={row.disposition} onChange={e=>editRow({disposition:e.target.value})}>{row.disposition==='imported'&&<option value="imported">Imported — immutable</option>}<option value="pending">Keep pending / source observation</option><option value="machine">Fresh machine production → OEE</option><option value="exclude">Exclude with reason</option></select></label>{row.disposition==='machine'&&<><label>Machine<select value={row.machine_id||''} onChange={e=>editRow({machine_id:Number(e.target.value)||null})}><option value="">Select machine</option>{machines.map(m=><option key={m.id} value={m.id}>{m.code} — {m.name}</option>)}</select></label><label>Product<select value={row.product_id||''} onChange={e=>editRow({product_id:Number(e.target.value)||null,route_operation_id:null,ideal_cycle_time_sec:null})}><option value="">Select product</option>{products.filter(p=>!draft.plant||p.plant===draft.plant).map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></label><label>Operation<select value={row.route_operation_id||''} onChange={e=>editRow({route_operation_id:Number(e.target.value)||null})}><option value="">Select effective operation</option>{routes.map((o:any)=><option key={o.route_operation_id} value={o.route_operation_id}>{o.operation} · revision {o.version}</option>)}</select></label><div className="form-row">{numberFields.map(k=><label key={k}>{labels[k]}<input type="number" min="0" step={['actual','good_count'].includes(k)?'1':'0.001'} value={row[k]??''} onChange={e=>editRow({[k]:e.target.value===''?null:Number(e.target.value)})}/></label>)}</div><p>Reject quantity = total − good. Blank timings remain unknown. Use the effective cycle-time master; no OEE is calculated from incomplete inputs.</p></>}<label>Row reason / confirmation<input value={row.reason} onChange={e=>editRow({reason:e.target.value})}/></label></fieldset>}</section>
 <section className="panel">{capture.receipt.length>0&&<p>{capture.receipt.length} machine records already imported. <Link to="/oee">Open Machine / OEE</Link></p>}<h2>4. Validate and import selected machine rows</h2>{!locked?<><button disabled={busy||dirty} onClick={()=>run(async()=>{setPreview(await api(`/shop-capture/${capture.id}/preview`,{method:'POST',body:JSON.stringify({revision:capture.revision})}))})}>Validate saved review</button>{dirty&&<p>Save your changes before validating.</p>}{preview&&<><p>{preview.new} machine rows · {preview.pending} pending source observations</p>{preview.errors.map((e:string,i:number)=><p className="error" key={i}>{e}</p>)}{preview.can_confirm&&<button disabled={busy||dirty} onClick={()=>run(async()=>{const x=await api(`/shop-capture/${capture.id}/confirm`,{method:'POST',body:JSON.stringify({revision:capture.revision})});load(x);await refresh();setMessage('Selected machine rows imported. Other observations remain retained in this report; they were not posted to business totals.')})}>Confirm machine import</button>}</>}</>:<><p>Selected machine rows imported. Remaining source observations are retained for follow-up.</p>{capture.receipt.map((r:any)=><p key={r.id}><Link to={`/oee`}>Machine #{r.machine_id} · {r.date} · {r.shift} · entry #{r.id}</Link></p>)}</>}<p>Existing machine shifts are blocked from duplicate import. Closed months require the normal historical-correction authorization.</p></section></>}
 </>
}
