import { useEffect, useMemo, useState } from 'react'
import { api, downloadApi } from '../api'
import { RankedBars, ValueTrendChart } from '../components/Charts'
import ImportPreview from '../components/ImportPreview'
import { Kpi, num, PageHeader } from '../components/UI'
import { MultiSelect } from '../components/MultiSelect'

type Mode='casting'|'customer'
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const today=()=>iso(new Date())
const monthAgo=()=>{const d=new Date();d.setDate(d.getDate()-30);return iso(d)}

function SpecialQuality({mode}:{mode:Mode}){
 const casting=mode==='casting', base=casting?'/casting-quality':'/customer-quality'
 const [products,setProducts]=useState<any[]>([]),[vendors,setVendors]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[phenomena,setPhenomena]=useState<any[]>([])
 const [fromDate,setFromDate]=useState(monthAgo()),[toDate,setToDate]=useState(today()),[productId,setProductId]=useState(''),[partyId,setPartyId]=useState(''),[phenomenonId,setPhenomenonId]=useState('')
 const [report,setReport]=useState<any>({summary:{},trend:[],phenomenon_pareto:[],product_pareto:[],customer_pareto:[],rows:[]}),[error,setError]=useState(''),[showEntry,setShowEntry]=useState(false),[saving,setSaving]=useState(false)
 const [entry,setEntry]=useState<any>(casting?{defect_date:today(),shift:'General',product_id:'',vendor_id:'',heat_batch_no:'',phenomenon_id:'',inspected_qty:'',defect_qty:'',rework_qty:'0',scrap_qty:'0',remark:''}:{rejection_date:today(),customer_id:'',product_id:'',reference_no:'',batch_no:'',phenomenon_id:'',dispatch_qty:'',reject_qty:'',remark:''})
 async function masters(){try{const [p,v,c,ph]=await Promise.all([api('/masters/products'),api('/masters/vendors'),api('/masters/customers'),api(`${base}/phenomena`)]);setProducts(p as any[]);setVendors(v as any[]);setCustomers(c as any[]);setPhenomena(ph as any[])}catch(e:any){setError(e.message)}}
 async function load(){try{setError('');const q=new URLSearchParams({from_date:fromDate,to_date:toDate});if(productId)q.set('product_id',productId);if(phenomenonId)q.set('phenomenon_id',phenomenonId);if(partyId)q.set(casting?'vendor_id':'customer_id',partyId);setReport(await api(`${base}/report?${q}`))}catch(e:any){setError(e.message)}}
 useEffect(()=>{masters()},[mode])
 useEffect(()=>{load()},[mode,fromDate,toDate,productId,partyId,phenomenonId])
 const availableProducts=useMemo(()=>!casting&&entry.customer_id?products.filter(p=>!p.customer_id||String(p.customer_id)===String(entry.customer_id)):products,[casting,entry.customer_id,products])
 async function addPhenomenon(){const name=prompt(`New ${casting?'casting defect':'customer rejection'} phenomenon`);if(!name)return;try{await api(`${base}/phenomena`,{method:'POST',body:JSON.stringify({name,criticality:'NORMAL'})});await masters()}catch(e:any){setError(e.message)}}
 async function save(){setSaving(true);setError('');try{
   const body=casting?{...entry,product_id:Number(entry.product_id),vendor_id:entry.vendor_id?Number(entry.vendor_id):null,phenomenon_id:Number(entry.phenomenon_id),inspected_qty:Number(entry.inspected_qty),defect_qty:Number(entry.defect_qty),rework_qty:Number(entry.rework_qty||0),scrap_qty:Number(entry.scrap_qty||0)}:{...entry,customer_id:Number(entry.customer_id),product_id:Number(entry.product_id),phenomenon_id:Number(entry.phenomenon_id),dispatch_qty:Number(entry.dispatch_qty),reject_qty:Number(entry.reject_qty)}
   const result:any=await api(`${base}/daily`,{method:'POST',body:JSON.stringify(body)});alert(`Saved. Calculated PPM: ${Math.round(result.ppm).toLocaleString('en-IN')}`);setShowEntry(false);await load()
 }catch(e:any){setError(e.message)}finally{setSaving(false)}}
 const s=report.summary||{},rejectKey=casting?'defect_qty':'reject_qty',denomKey=casting?'inspected_qty':'dispatch_qty'
 return <><PageHeader title={casting?'Casting Quality':'Customer Quality'} subtitle={casting?'Incoming casting defects, rework, scrap, PPM and phenomenon Pareto.':'Customer rejection, customer PPM, complaint references and phenomenon Pareto.'} actions={<div className="button-row"><button onClick={()=>setShowEntry(!showEntry)}>{showEntry?'Close Entry':casting?'+ Add Casting Defect':'+ Add Customer Rejection'}</button><button className="secondary" onClick={()=>downloadApi(`${base}/template`,casting?'Casting_Defect_Upload_v0.5.6.xlsx':'Customer_Rejection_Upload_v0.5.6.xlsx')}>Download Template</button><button onClick={()=>window.print()}>Print / PDF</button></div>}/>
 {showEntry&&<section className="panel"><h2>{casting?'Add Casting Defect':'Add Customer Rejection'}</h2><div className="quality-entry-grid">
  <label>Date<input type="date" value={entry[casting?'defect_date':'rejection_date']} onChange={e=>setEntry({...entry,[casting?'defect_date':'rejection_date']:e.target.value})}/></label>
  {casting?<label>Shift<select value={entry.shift} onChange={e=>setEntry({...entry,shift:e.target.value})}>{['A','B','C','General'].map(x=><option key={x}>{x}</option>)}</select></label>:<label>Customer<MultiSelect className="manual-search-select" value={entry.customer_id?[String(entry.customer_id)]:[]} onChange={v=>setEntry({...entry,customer_id:v.at(-1)||'',product_id:''})} placeholder="Select Customer" options={customers.map(x=>({value:String(x.id),label:x.name}))}/></label>}
  <label>Product<MultiSelect className="manual-search-select" value={entry.product_id?[String(entry.product_id)]:[]} onChange={v=>setEntry({...entry,product_id:v.at(-1)||''})} placeholder="Select Product" options={availableProducts.map(x=>({value:String(x.id),label:x.name}))}/></label>
  {casting?<><label>Vendor<MultiSelect className="manual-search-select" value={entry.vendor_id?[String(entry.vendor_id)]:[]} onChange={v=>setEntry({...entry,vendor_id:v.at(-1)||''})} placeholder="Optional" options={vendors.map(x=>({value:String(x.id),label:x.name}))}/></label><label>Heat / Batch No<input value={entry.heat_batch_no} onChange={e=>setEntry({...entry,heat_batch_no:e.target.value})}/></label></>:<><label>Complaint / Reference No<input value={entry.reference_no} onChange={e=>setEntry({...entry,reference_no:e.target.value})}/></label><label>Batch No<input value={entry.batch_no} onChange={e=>setEntry({...entry,batch_no:e.target.value})}/></label></>}
  <label>Phenomenon<MultiSelect className="manual-search-select" value={entry.phenomenon_id?[String(entry.phenomenon_id)]:[]} onChange={v=>setEntry({...entry,phenomenon_id:v.at(-1)||''})} placeholder="Select Phenomenon" options={phenomena.filter(x=>x.active!==false).map(x=>({value:String(x.id),label:x.name}))}/></label>
  <label>{casting?'Inspected Qty':'Dispatch / Received Qty'}<input type="number" min="0.001" step="0.001" value={entry[casting?'inspected_qty':'dispatch_qty']} onChange={e=>setEntry({...entry,[casting?'inspected_qty':'dispatch_qty']:e.target.value})}/></label>
  <label>{casting?'Defect Qty':'Reject Qty'}<input type="number" min="0" step="0.001" value={entry[casting?'defect_qty':'reject_qty']} onChange={e=>setEntry({...entry,[casting?'defect_qty':'reject_qty']:e.target.value})}/></label>
  {casting&&<><label>Rework Qty<input type="number" min="0" step="0.001" value={entry.rework_qty} onChange={e=>setEntry({...entry,rework_qty:e.target.value})}/></label><label>Scrap Qty<input type="number" min="0" step="0.001" value={entry.scrap_qty} onChange={e=>setEntry({...entry,scrap_qty:e.target.value})}/></label></>}
  <label className="span-2">Remark<textarea value={entry.remark} onChange={e=>setEntry({...entry,remark:e.target.value})}/></label></div><div className="button-row"><button disabled={saving} onClick={save}>{saving?'Saving…':'Save'}</button><button className="secondary" onClick={()=>setShowEntry(false)}>Cancel</button></div></section>}
 <section className="panel"><div className="filters"><label>From<input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/></label><label>To<input type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/></label><label>Product<MultiSelect className="manual-search-select" value={productId?[productId]:[]} onChange={v=>setProductId(v.at(-1)||'')} placeholder="All Products" options={products.map(x=>({value:String(x.id),label:x.name}))}/></label><label>{casting?'Vendor':'Customer'}<MultiSelect className="manual-search-select" value={partyId?[partyId]:[]} onChange={v=>setPartyId(v.at(-1)||'')} placeholder="All" options={(casting?vendors:customers).map(x=>({value:String(x.id),label:x.name}))}/></label><label>Phenomenon<MultiSelect className="manual-search-select" value={phenomenonId?[phenomenonId]:[]} onChange={v=>setPhenomenonId(v.at(-1)||'')} placeholder="All Phenomena" options={phenomena.map(x=>({value:String(x.id),label:x.name}))}/></label></div>{error&&<div className="error">{error}</div>}</section>
 <div className="kpi-grid"><Kpi label={casting?'Defect Qty':'Customer Reject Qty'} value={num(s[rejectKey]||0)} tone={s[rejectKey]>0?'bad':'good'}/><Kpi label="PPM" value={Math.round(s.ppm||0).toLocaleString('en-IN')}/><Kpi label={casting?'Inspected Qty':'Dispatch / Received Qty'} value={num(s[denomKey]||0)}/>{casting&&<><Kpi label="Rework Qty" value={num(s.rework_qty||0)}/><Kpi label="Scrap Qty" value={num(s.scrap_qty||0)} tone={s.scrap_qty>0?'bad':'neutral'}/></>}<Kpi label="Records" value={s.records||0}/></div>
 <section className="panel"><div className="panel-title"><h2>PPM Trend</h2><span>Weighted from daily quantities</span></div><ValueTrendChart rows={(report.trend||[]).map((x:any)=>({...x,value:x.ppm}))} keyName="value" label="PPM"/></section>
 <div className="two-col"><section className="panel"><h2>Phenomenon Pareto</h2><RankedBars rows={report.phenomenon_pareto||[]} valueKey={rejectKey} labelKey="name" valueLabel={casting?'Defect Qty':'Reject Qty'}/></section><section className="panel"><h2>{casting?'Product':'Customer'} Pareto</h2><RankedBars rows={(casting?report.product_pareto:report.customer_pareto)||[]} valueKey={rejectKey} labelKey="name" valueLabel={casting?'Defect Qty':'Reject Qty'}/></section></div>
 <section className="panel"><div className="panel-title"><h2>{casting?'Casting':'Customer Rejection'} Phenomenon Master</h2><button onClick={addPhenomenon}>Add Phenomenon</button></div><p className="muted">Unknown typed phenomena are rejected during import. Add the approved name here, then download a fresh template.</p><div className="table-wrap"><table><thead><tr><th>Code</th><th>Phenomenon</th><th>Group</th><th>Criticality</th></tr></thead><tbody>{phenomena.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.name}</td><td>{x.phenomenon_group||'—'}</td><td>{x.criticality}</td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2>Controlled Excel Import</h2><p>Use the current template. Preview validates file content, master values, quantities and duplicate business keys before anything is committed.</p><ImportPreview kind={casting?'casting-daily':'customer-quality-daily'} onComplete={()=>{masters();load()}}/></section>
 <section className="panel"><div className="panel-title"><h2>Detail</h2><span>{(report.rows||[]).length} records</span></div><div className="table-wrap"><table><thead><tr><th>Date</th>{!casting&&<th>Customer</th>}<th>Product</th>{casting?<><th>Vendor</th><th>Heat / Batch</th></>:<><th>Reference</th><th>Batch</th></>}<th>Phenomenon</th><th>{casting?'Inspected':'Dispatch / Received'}</th><th>{casting?'Defect':'Reject'}</th>{casting&&<><th>Rework</th><th>Scrap</th></>}<th>PPM</th><th>Remark</th></tr></thead><tbody>{(report.rows||[]).map((r:any)=><tr key={r.id}><td>{r.date}</td>{!casting&&<td>{r.customer}</td>}<td>{r.product}</td>{casting?<><td>{r.vendor||'—'}</td><td>{r.heat_batch_no||'—'}</td></>:<><td>{r.reference_no||'—'}</td><td>{r.batch_no||'—'}</td></>}<td>{r.phenomenon}</td><td>{num(r[denomKey])}</td><td><b>{num(r[rejectKey])}</b></td>{casting&&<><td>{num(r.rework_qty)}</td><td>{num(r.scrap_qty)}</td></>}<td>{Math.round(r.ppm).toLocaleString('en-IN')}</td><td>{r.remark||''}</td></tr>)}</tbody></table></div></section>
 </>
}

export function CastingQuality(){return <SpecialQuality mode="casting"/>}
export function CustomerQuality(){return <SpecialQuality mode="customer"/>}
