import { useEffect, useState } from 'react'
import { api } from '../api'
import { PageHeader, num } from '../components/UI'
function today(){return new Date().toISOString().slice(0,10)}
export default function Vendor(){
 const [rows,setRows]=useState<any[]>([]); const [only,setOnly]=useState(true); const [products,setProducts]=useState<any[]>([]); const [vendors,setVendors]=useState<any[]>([]); const [ops,setOps]=useState<any[]>([])
 const [form,setForm]=useState<any>({product_id:'',route_operation_id:'',vendor_id:'',outward_date:today(),outward_qty:'',challan_no:'',expected_return_date:'',remarks:''})
 async function load(){setRows(await api(`/vendor/movements?pending_only=${only}`))}
 useEffect(()=>{load();api('/masters/products').then((x:any)=>{setProducts(x);if(x[0])setForm((f:any)=>({...f,product_id:String(x[0].id)}))});api('/masters/vendors').then((x:any)=>{setVendors(x);if(x[0])setForm((f:any)=>({...f,vendor_id:String(x[0].id)}))})},[])
 useEffect(()=>{load()},[only])
 useEffect(()=>{if(form.product_id)api(`/masters/routes/${form.product_id}`).then((x:any)=>{const list=x[0]?.operations||[];setOps(list);const vendorOps=list.filter((o:any)=>o.type.startsWith('VENDOR'));setForm((f:any)=>({...f,route_operation_id:String((vendorOps[0]||list[0]||{}).route_operation_id||'')}))})},[form.product_id])
 async function receive(r:any){const qty=prompt(`Receipt qty for ${r.product} / ${r.vendor}`,String(r.pending_qty));if(qty==null)return; const reject=prompt('Reject qty','0')||'0'; const d=today(); await api(`/vendor/movements/${r.id}/receipt?receipt_date=${d}&receipt_qty=${Number(qty)}&reject_qty=${Number(reject)}`,{method:'PATCH'});load()}
 async function outward(e:React.FormEvent){e.preventDefault();await api('/vendor/movements',{method:'POST',body:JSON.stringify({...form,product_id:Number(form.product_id),route_operation_id:Number(form.route_operation_id),vendor_id:Number(form.vendor_id),outward_qty:Number(form.outward_qty),expected_return_date:form.expected_return_date||null,receipt_date:null,receipt_qty:0,reject_qty:0})});setForm({...form,outward_qty:'',challan_no:'',remarks:''});load()}
 return <><PageHeader title="Vendor WIP" subtitle="Outward, inward, pending quantity, aging and overdue vendor operations." actions={<label className="inline-check"><input type="checkbox" checked={only} onChange={e=>setOnly(e.target.checked)}/> Pending only</label>}/>
 <div className="two-col wide-left"><section className="panel"><div className="table-wrap"><table><thead><tr><th>Product</th><th>Operation</th><th>Vendor</th><th>Outward</th><th>Sent</th><th>Received</th><th>Pending</th><th>Expected</th><th>Age</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className={r.overdue?'row-overdue':''}><td><b>{r.product}</b></td><td>{r.operation}</td><td>{r.vendor}</td><td>{r.outward_date}</td><td>{num(r.outward_qty)}</td><td>{num(r.receipt_qty)}</td><td className={r.pending_qty>0?'neg':'pos'}>{num(r.pending_qty)}</td><td>{r.expected_return_date||'—'}</td><td>{r.age_days}d</td><td>{r.pending_qty>0&&<button className="small" onClick={()=>receive(r)}>Receive</button>}</td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2>Vendor outward</h2><form onSubmit={outward}><label>Product<select value={form.product_id} onChange={e=>setForm({...form,product_id:e.target.value})}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Operation<select value={form.route_operation_id} onChange={e=>setForm({...form,route_operation_id:e.target.value})}>{ops.map(o=><option key={o.route_operation_id} value={o.route_operation_id}>{o.operation} — {o.type}</option>)}</select></label><label>Vendor<select value={form.vendor_id} onChange={e=>setForm({...form,vendor_id:e.target.value})}>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Outward date<input type="date" value={form.outward_date} onChange={e=>setForm({...form,outward_date:e.target.value})}/></label><label>Qty<input required type="number" value={form.outward_qty} onChange={e=>setForm({...form,outward_qty:e.target.value})}/></label><label>Challan No<input value={form.challan_no} onChange={e=>setForm({...form,challan_no:e.target.value})}/></label><label>Expected return<input type="date" value={form.expected_return_date} onChange={e=>setForm({...form,expected_return_date:e.target.value})}/></label><label>Remarks<textarea value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></label><button>Create outward</button></form></section></div></>
}
